// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: derivaciones_service.proto

package server

import (
	"context"

	"derivaciones/derivaciones"
	"derivaciones/internal/logic"
	"derivaciones/internal/svc"
)

type DerivacionesServer struct {
	svcCtx *svc.ServiceContext
	derivaciones.UnimplementedDerivacionesServer
}

func NewDerivacionesServer(svcCtx *svc.ServiceContext) *DerivacionesServer {
	return &DerivacionesServer{
		svcCtx: svcCtx,
	}
}

func (s *DerivacionesServer) CrearDerivacion(ctx context.Context, in *derivaciones.CrearDerivacionRequest) (*derivaciones.CrearDerivacionResponse, error) {
	l := logic.NewCrearDerivacionLogic(ctx, s.svcCtx)
	return l.CrearDerivacion(in)
}

func (s *DerivacionesServer) GetDerivacion(ctx context.Context, in *derivaciones.GetDerivacionRequest) (*derivaciones.GetDerivacionResponse, error) {
	l := logic.NewGetDerivacionLogic(ctx, s.svcCtx)
	return l.GetDerivacion(in)
}

func (s *DerivacionesServer) ListDerivaciones(ctx context.Context, in *derivaciones.ListDerivacionesRequest) (*derivaciones.ListDerivacionesResponse, error) {
	l := logic.NewListDerivacionesLogic(ctx, s.svcCtx)
	return l.ListDerivaciones(in)
}
