// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: documentos_service.proto

package server

import (
	"context"

	"documentos/documentos"
	"documentos/internal/logic"
	"documentos/internal/svc"
)

type DocumentosServer struct {
	svcCtx *svc.ServiceContext
	documentos.UnimplementedDocumentosServer
}

func NewDocumentosServer(svcCtx *svc.ServiceContext) *DocumentosServer {
	return &DocumentosServer{
		svcCtx: svcCtx,
	}
}

func (s *DocumentosServer) UploadDocumento(ctx context.Context, in *documentos.UploadDocumentoRequest) (*documentos.UploadDocumentoResponse, error) {
	l := logic.NewUploadDocumentoLogic(ctx, s.svcCtx)
	return l.UploadDocumento(in)
}

func (s *DocumentosServer) GetDocumento(ctx context.Context, in *documentos.GetDocumentoRequest) (*documentos.GetDocumentoResponse, error) {
	l := logic.NewGetDocumentoLogic(ctx, s.svcCtx)
	return l.GetDocumento(in)
}

func (s *DocumentosServer) DownloadDocumento(ctx context.Context, in *documentos.DownloadDocumentoRequest) (*documentos.DownloadDocumentoResponse, error) {
	l := logic.NewDownloadDocumentoLogic(ctx, s.svcCtx)
	return l.DownloadDocumento(in)
}

func (s *DocumentosServer) ListDocumentos(ctx context.Context, in *documentos.ListDocumentosRequest) (*documentos.ListDocumentosResponse, error) {
	l := logic.NewListDocumentosLogic(ctx, s.svcCtx)
	return l.ListDocumentos(in)
}

func (s *DocumentosServer) DeleteDocumento(ctx context.Context, in *documentos.DeleteDocumentoRequest) (*documentos.DeleteDocumentoResponse, error) {
	l := logic.NewDeleteDocumentoLogic(ctx, s.svcCtx)
	return l.DeleteDocumento(in)
}
