// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: auth_service.proto

package server

import (
	"context"

	"auth/auth"
	"auth/internal/logic"
	"auth/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Ping(ctx context.Context, in *auth.Request) (*auth.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *AuthServer) Register(ctx context.Context, in *auth.RegisterRequest) (*auth.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServer) Login(ctx context.Context, in *auth.LoginRequest) (*auth.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServer) RefreshToken(ctx context.Context, in *auth.RefreshTokenRequest) (*auth.RefreshTokenResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AuthServer) Logout(ctx context.Context, in *auth.LogoutRequest) (*auth.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *AuthServer) ValidateToken(ctx context.Context, in *auth.ValidateTokenRequest) (*auth.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServer) HasPermission(ctx context.Context, in *auth.HasPermissionRequest) (*auth.HasPermissionResponse, error) {
	l := logic.NewHasPermissionLogic(ctx, s.svcCtx)
	return l.HasPermission(in)
}

func (s *AuthServer) ListRoles(ctx context.Context, in *auth.ListRolesRequest) (*auth.ListRolesResponse, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *AuthServer) ListPermissions(ctx context.Context, in *auth.ListPermissionsRequest) (*auth.ListPermissionsResponse, error) {
	l := logic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

func (s *AuthServer) GetRolePermissions(ctx context.Context, in *auth.GetRolePermissionsRequest) (*auth.GetRolePermissionsResponse, error) {
	l := logic.NewGetRolePermissionsLogic(ctx, s.svcCtx)
	return l.GetRolePermissions(in)
}

func (s *AuthServer) UpdateRolePermissions(ctx context.Context, in *auth.UpdateRolePermissionsRequest) (*auth.UpdateRolePermissionsResponse, error) {
	l := logic.NewUpdateRolePermissionsLogic(ctx, s.svcCtx)
	return l.UpdateRolePermissions(in)
}
