// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: expedientes_service.proto

package expedientes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Expedientes_CreateExpediente_FullMethodName = "/expedientes.Expedientes/CreateExpediente"
	Expedientes_GetExpediente_FullMethodName    = "/expedientes.Expedientes/GetExpediente"
	Expedientes_ListExpedientes_FullMethodName  = "/expedientes.Expedientes/ListExpedientes"
	Expedientes_UpdateExpediente_FullMethodName = "/expedientes.Expedientes/UpdateExpediente"
	Expedientes_ChangeEstado_FullMethodName     = "/expedientes.Expedientes/ChangeEstado"
)

// ExpedientesClient is the client API for Expedientes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExpedientesClient interface {
	CreateExpediente(ctx context.Context, in *CreateExpedienteRequest, opts ...grpc.CallOption) (*CreateExpedienteResponse, error)
	GetExpediente(ctx context.Context, in *GetExpedienteRequest, opts ...grpc.CallOption) (*GetExpedienteResponse, error)
	ListExpedientes(ctx context.Context, in *ListExpedientesRequest, opts ...grpc.CallOption) (*ListExpedientesResponse, error)
	UpdateExpediente(ctx context.Context, in *UpdateExpedienteRequest, opts ...grpc.CallOption) (*UpdateExpedienteResponse, error)
	ChangeEstado(ctx context.Context, in *ChangeEstadoRequest, opts ...grpc.CallOption) (*ChangeEstadoResponse, error)
}

type expedientesClient struct {
	cc grpc.ClientConnInterface
}

func NewExpedientesClient(cc grpc.ClientConnInterface) ExpedientesClient {
	return &expedientesClient{cc}
}

func (c *expedientesClient) CreateExpediente(ctx context.Context, in *CreateExpedienteRequest, opts ...grpc.CallOption) (*CreateExpedienteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExpedienteResponse)
	err := c.cc.Invoke(ctx, Expedientes_CreateExpediente_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expedientesClient) GetExpediente(ctx context.Context, in *GetExpedienteRequest, opts ...grpc.CallOption) (*GetExpedienteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpedienteResponse)
	err := c.cc.Invoke(ctx, Expedientes_GetExpediente_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expedientesClient) ListExpedientes(ctx context.Context, in *ListExpedientesRequest, opts ...grpc.CallOption) (*ListExpedientesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExpedientesResponse)
	err := c.cc.Invoke(ctx, Expedientes_ListExpedientes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expedientesClient) UpdateExpediente(ctx context.Context, in *UpdateExpedienteRequest, opts ...grpc.CallOption) (*UpdateExpedienteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateExpedienteResponse)
	err := c.cc.Invoke(ctx, Expedientes_UpdateExpediente_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *expedientesClient) ChangeEstado(ctx context.Context, in *ChangeEstadoRequest, opts ...grpc.CallOption) (*ChangeEstadoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeEstadoResponse)
	err := c.cc.Invoke(ctx, Expedientes_ChangeEstado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpedientesServer is the server API for Expedientes service.
// All implementations must embed UnimplementedExpedientesServer
// for forward compatibility.
type ExpedientesServer interface {
	CreateExpediente(context.Context, *CreateExpedienteRequest) (*CreateExpedienteResponse, error)
	GetExpediente(context.Context, *GetExpedienteRequest) (*GetExpedienteResponse, error)
	ListExpedientes(context.Context, *ListExpedientesRequest) (*ListExpedientesResponse, error)
	UpdateExpediente(context.Context, *UpdateExpedienteRequest) (*UpdateExpedienteResponse, error)
	ChangeEstado(context.Context, *ChangeEstadoRequest) (*ChangeEstadoResponse, error)
	mustEmbedUnimplementedExpedientesServer()
}

// UnimplementedExpedientesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExpedientesServer struct{}

func (UnimplementedExpedientesServer) CreateExpediente(context.Context, *CreateExpedienteRequest) (*CreateExpedienteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExpediente not implemented")
}
func (UnimplementedExpedientesServer) GetExpediente(context.Context, *GetExpedienteRequest) (*GetExpedienteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExpediente not implemented")
}
func (UnimplementedExpedientesServer) ListExpedientes(context.Context, *ListExpedientesRequest) (*ListExpedientesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExpedientes not implemented")
}
func (UnimplementedExpedientesServer) UpdateExpediente(context.Context, *UpdateExpedienteRequest) (*UpdateExpedienteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExpediente not implemented")
}
func (UnimplementedExpedientesServer) ChangeEstado(context.Context, *ChangeEstadoRequest) (*ChangeEstadoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeEstado not implemented")
}
func (UnimplementedExpedientesServer) mustEmbedUnimplementedExpedientesServer() {}
func (UnimplementedExpedientesServer) testEmbeddedByValue()                     {}

// UnsafeExpedientesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExpedientesServer will
// result in compilation errors.
type UnsafeExpedientesServer interface {
	mustEmbedUnimplementedExpedientesServer()
}

func RegisterExpedientesServer(s grpc.ServiceRegistrar, srv ExpedientesServer) {
	// If the following call panics, it indicates UnimplementedExpedientesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Expedientes_ServiceDesc, srv)
}

func _Expedientes_CreateExpediente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExpedienteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpedientesServer).CreateExpediente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expedientes_CreateExpediente_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpedientesServer).CreateExpediente(ctx, req.(*CreateExpedienteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expedientes_GetExpediente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpedienteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpedientesServer).GetExpediente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expedientes_GetExpediente_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpedientesServer).GetExpediente(ctx, req.(*GetExpedienteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expedientes_ListExpedientes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpedientesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpedientesServer).ListExpedientes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expedientes_ListExpedientes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpedientesServer).ListExpedientes(ctx, req.(*ListExpedientesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expedientes_UpdateExpediente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExpedienteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpedientesServer).UpdateExpediente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expedientes_UpdateExpediente_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpedientesServer).UpdateExpediente(ctx, req.(*UpdateExpedienteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Expedientes_ChangeEstado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEstadoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpedientesServer).ChangeEstado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Expedientes_ChangeEstado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpedientesServer).ChangeEstado(ctx, req.(*ChangeEstadoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Expedientes_ServiceDesc is the grpc.ServiceDesc for Expedientes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Expedientes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "expedientes.Expedientes",
	HandlerType: (*ExpedientesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExpediente",
			Handler:    _Expedientes_CreateExpediente_Handler,
		},
		{
			MethodName: "GetExpediente",
			Handler:    _Expedientes_GetExpediente_Handler,
		},
		{
			MethodName: "ListExpedientes",
			Handler:    _Expedientes_ListExpedientes_Handler,
		},
		{
			MethodName: "UpdateExpediente",
			Handler:    _Expedientes_UpdateExpediente_Handler,
		},
		{
			MethodName: "ChangeEstado",
			Handler:    _Expedientes_ChangeEstado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expedientes_service.proto",
}
