// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: expedientes_service.proto

package expedientes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expediente struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Codigo             string                 `protobuf:"bytes,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Tipo               string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Asunto             string                 `protobuf:"bytes,4,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion        string                 `protobuf:"bytes,5,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	SolicitanteId      string                 `protobuf:"bytes,6,opt,name=solicitante_id,json=solicitanteId,proto3" json:"solicitante_id,omitempty"`
	Estado             string                 `protobuf:"bytes,7,opt,name=estado,proto3" json:"estado,omitempty"`
	Prioridad          string                 `protobuf:"bytes,8,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	FechaRegistro      string                 `protobuf:"bytes,9,opt,name=fecha_registro,json=fechaRegistro,proto3" json:"fecha_registro,omitempty"`
	FechaActualizacion string                 `protobuf:"bytes,10,opt,name=fecha_actualizacion,json=fechaActualizacion,proto3" json:"fecha_actualizacion,omitempty"`
	Activo             bool                   `protobuf:"varint,11,opt,name=activo,proto3" json:"activo,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Expediente) Reset() {
	*x = Expediente{}
	mi := &file_expedientes_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expediente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expediente) ProtoMessage() {}

func (x *Expediente) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expediente.ProtoReflect.Descriptor instead.
func (*Expediente) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{0}
}

func (x *Expediente) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expediente) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Expediente) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Expediente) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *Expediente) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Expediente) GetSolicitanteId() string {
	if x != nil {
		return x.SolicitanteId
	}
	return ""
}

func (x *Expediente) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Expediente) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

func (x *Expediente) GetFechaRegistro() string {
	if x != nil {
		return x.FechaRegistro
	}
	return ""
}

func (x *Expediente) GetFechaActualizacion() string {
	if x != nil {
		return x.FechaActualizacion
	}
	return ""
}

func (x *Expediente) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

type CreateExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Asunto        string                 `protobuf:"bytes,2,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Prioridad     string                 `protobuf:"bytes,4,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpedienteRequest) Reset() {
	*x = CreateExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpedienteRequest) ProtoMessage() {}

func (x *CreateExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpedienteRequest.ProtoReflect.Descriptor instead.
func (*CreateExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpedienteRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CreateExpedienteRequest) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *CreateExpedienteRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreateExpedienteRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

type CreateExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpedienteResponse) Reset() {
	*x = CreateExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpedienteResponse) ProtoMessage() {}

func (x *CreateExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpedienteResponse.ProtoReflect.Descriptor instead.
func (*CreateExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type GetExpedienteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Acepta el UUID interno o el codigo legible (EXP-2026-000001).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpedienteRequest) Reset() {
	*x = GetExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpedienteRequest) ProtoMessage() {}

func (x *GetExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpedienteRequest.ProtoReflect.Descriptor instead.
func (*GetExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpedienteResponse) Reset() {
	*x = GetExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpedienteResponse) ProtoMessage() {}

func (x *GetExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpedienteResponse.ProtoReflect.Descriptor instead.
func (*GetExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type ListExpedientesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Prioridad     string                 `protobuf:"bytes,2,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpedientesRequest) Reset() {
	*x = ListExpedientesRequest{}
	mi := &file_expedientes_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpedientesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpedientesRequest) ProtoMessage() {}

func (x *ListExpedientesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpedientesRequest.ProtoReflect.Descriptor instead.
func (*ListExpedientesRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListExpedientesRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ListExpedientesRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

func (x *ListExpedientesRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ListExpedientesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExpedientesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListExpedientesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expedientes   []*Expediente          `protobuf:"bytes,1,rep,name=expedientes,proto3" json:"expedientes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpedientesResponse) Reset() {
	*x = ListExpedientesResponse{}
	mi := &file_expedientes_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpedientesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpedientesResponse) ProtoMessage() {}

func (x *ListExpedientesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpedientesResponse.ProtoReflect.Descriptor instead.
func (*ListExpedientesResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListExpedientesResponse) GetExpedientes() []*Expediente {
	if x != nil {
		return x.Expedientes
	}
	return nil
}

func (x *ListExpedientesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Asunto        string                 `protobuf:"bytes,2,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Prioridad     string                 `protobuf:"bytes,4,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpedienteRequest) Reset() {
	*x = UpdateExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpedienteRequest) ProtoMessage() {}

func (x *UpdateExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpedienteRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

type UpdateExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpedienteResponse) Reset() {
	*x = UpdateExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpedienteResponse) ProtoMessage() {}

func (x *UpdateExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpedienteResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type ChangeEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NuevoEstado   string                 `protobuf:"bytes,2,opt,name=nuevo_estado,json=nuevoEstado,proto3" json:"nuevo_estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEstadoRequest) Reset() {
	*x = ChangeEstadoRequest{}
	mi := &file_expedientes_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEstadoRequest) ProtoMessage() {}

func (x *ChangeEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEstadoRequest.ProtoReflect.Descriptor instead.
func (*ChangeEstadoRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeEstadoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeEstadoRequest) GetNuevoEstado() string {
	if x != nil {
		return x.NuevoEstado
	}
	return ""
}

type ChangeEstadoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEstadoResponse) Reset() {
	*x = ChangeEstadoResponse{}
	mi := &file_expedientes_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEstadoResponse) ProtoMessage() {}

func (x *ChangeEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEstadoResponse.ProtoReflect.Descriptor instead.
func (*ChangeEstadoResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeEstadoResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

var File_expedientes_service_proto protoreflect.FileDescriptor

const file_expedientes_service_proto_rawDesc = "" +
	"\n" +
	"\x19expedientes_service.proto\x12\vexpedientes\"\xcf\x02\n" +
	"\n" +
	"Expediente\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\tR\x06codigo\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06asunto\x18\x04 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x05 \x01(\tR\vdescripcion\x12%\n" +
	"\x0esolicitante_id\x18\x06 \x01(\tR\rsolicitanteId\x12\x16\n" +
	"\x06estado\x18\a \x01(\tR\x06estado\x12\x1c\n" +
	"\tprioridad\x18\b \x01(\tR\tprioridad\x12%\n" +
	"\x0efecha_registro\x18\t \x01(\tR\rfechaRegistro\x12/\n" +
	"\x13fecha_actualizacion\x18\n" +
	" \x01(\tR\x12fechaActualizacion\x12\x16\n" +
	"\x06activo\x18\v \x01(\bR\x06activo\"\x85\x01\n" +
	"\x17CreateExpedienteRequest\x12\x12\n" +
	"\x04tipo\x18\x01 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06asunto\x18\x02 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x1c\n" +
	"\tprioridad\x18\x04 \x01(\tR\tprioridad\"S\n" +
	"\x18CreateExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"&\n" +
	"\x14GetExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x15GetExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"\x93\x01\n" +
	"\x16ListExpedientesRequest\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12\x1c\n" +
	"\tprioridad\x18\x02 \x01(\tR\tprioridad\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"j\n" +
	"\x17ListExpedientesResponse\x129\n" +
	"\vexpedientes\x18\x01 \x03(\v2\x17.expedientes.ExpedienteR\vexpedientes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x81\x01\n" +
	"\x17UpdateExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06asunto\x18\x02 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x1c\n" +
	"\tprioridad\x18\x04 \x01(\tR\tprioridad\"S\n" +
	"\x18UpdateExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"H\n" +
	"\x13ChangeEstadoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fnuevo_estado\x18\x02 \x01(\tR\vnuevoEstado\"O\n" +
	"\x14ChangeEstadoResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente2\xda\x03\n" +
	"\vExpedientes\x12_\n" +
	"\x10CreateExpediente\x12$.expedientes.CreateExpedienteRequest\x1a%.expedientes.CreateExpedienteResponse\x12V\n" +
	"\rGetExpediente\x12!.expedientes.GetExpedienteRequest\x1a\".expedientes.GetExpedienteResponse\x12\\\n" +
	"\x0fListExpedientes\x12#.expedientes.ListExpedientesRequest\x1a$.expedientes.ListExpedientesResponse\x12_\n" +
	"\x10UpdateExpediente\x12$.expedientes.UpdateExpedienteRequest\x1a%.expedientes.UpdateExpedienteResponse\x12S\n" +
	"\fChangeEstado\x12 .expedientes.ChangeEstadoRequest\x1a!.expedientes.ChangeEstadoResponseB\x0fZ\r./expedientesb\x06proto3"

var (
	file_expedientes_service_proto_rawDescOnce sync.Once
	file_expedientes_service_proto_rawDescData []byte
)

func file_expedientes_service_proto_rawDescGZIP() []byte {
	file_expedientes_service_proto_rawDescOnce.Do(func() {
		file_expedientes_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expedientes_service_proto_rawDesc), len(file_expedientes_service_proto_rawDesc)))
	})
	return file_expedientes_service_proto_rawDescData
}

var file_expedientes_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_expedientes_service_proto_goTypes = []any{
	(*Expediente)(nil),               // 0: expedientes.Expediente
	(*CreateExpedienteRequest)(nil),  // 1: expedientes.CreateExpedienteRequest
	(*CreateExpedienteResponse)(nil), // 2: expedientes.CreateExpedienteResponse
	(*GetExpedienteRequest)(nil),     // 3: expedientes.GetExpedienteRequest
	(*GetExpedienteResponse)(nil),    // 4: expedientes.GetExpedienteResponse
	(*ListExpedientesRequest)(nil),   // 5: expedientes.ListExpedientesRequest
	(*ListExpedientesResponse)(nil),  // 6: expedientes.ListExpedientesResponse
	(*UpdateExpedienteRequest)(nil),  // 7: expedientes.UpdateExpedienteRequest
	(*UpdateExpedienteResponse)(nil), // 8: expedientes.UpdateExpedienteResponse
	(*ChangeEstadoRequest)(nil),      // 9: expedientes.ChangeEstadoRequest
	(*ChangeEstadoResponse)(nil),     // 10: expedientes.ChangeEstadoResponse
}
var file_expedientes_service_proto_depIdxs = []int32{
	0,  // 0: expedientes.CreateExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 1: expedientes.GetExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 2: expedientes.ListExpedientesResponse.expedientes:type_name -> expedientes.Expediente
	0,  // 3: expedientes.UpdateExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 4: expedientes.ChangeEstadoResponse.expediente:type_name -> expedientes.Expediente
	1,  // 5: expedientes.Expedientes.CreateExpediente:input_type -> expedientes.CreateExpedienteRequest
	3,  // 6: expedientes.Expedientes.GetExpediente:input_type -> expedientes.GetExpedienteRequest
	5,  // 7: expedientes.Expedientes.ListExpedientes:input_type -> expedientes.ListExpedientesRequest
	7,  // 8: expedientes.Expedientes.UpdateExpediente:input_type -> expedientes.UpdateExpedienteRequest
	9,  // 9: expedientes.Expedientes.ChangeEstado:input_type -> expedientes.ChangeEstadoRequest
	2,  // 10: expedientes.Expedientes.CreateExpediente:output_type -> expedientes.CreateExpedienteResponse
	4,  // 11: expedientes.Expedientes.GetExpediente:output_type -> expedientes.GetExpedienteResponse
	6,  // 12: expedientes.Expedientes.ListExpedientes:output_type -> expedientes.ListExpedientesResponse
	8,  // 13: expedientes.Expedientes.UpdateExpediente:output_type -> expedientes.UpdateExpedienteResponse
	10, // 14: expedientes.Expedientes.ChangeEstado:output_type -> expedientes.ChangeEstadoResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_expedientes_service_proto_init() }
func file_expedientes_service_proto_init() {
	if File_expedientes_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expedientes_service_proto_rawDesc), len(file_expedientes_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expedientes_service_proto_goTypes,
		DependencyIndexes: file_expedientes_service_proto_depIdxs,
		MessageInfos:      file_expedientes_service_proto_msgTypes,
	}.Build()
	File_expedientes_service_proto = out.File
	file_expedientes_service_proto_goTypes = nil
	file_expedientes_service_proto_depIdxs = nil
}
