// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: expedientes_service.proto

package expedientes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expediente struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Codigo             string                 `protobuf:"bytes,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Tipo               string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Asunto             string                 `protobuf:"bytes,4,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion        string                 `protobuf:"bytes,5,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	SolicitanteId      string                 `protobuf:"bytes,6,opt,name=solicitante_id,json=solicitanteId,proto3" json:"solicitante_id,omitempty"`
	Estado             string                 `protobuf:"bytes,7,opt,name=estado,proto3" json:"estado,omitempty"`
	Prioridad          string                 `protobuf:"bytes,8,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	FechaRegistro      string                 `protobuf:"bytes,9,opt,name=fecha_registro,json=fechaRegistro,proto3" json:"fecha_registro,omitempty"`
	FechaActualizacion string                 `protobuf:"bytes,10,opt,name=fecha_actualizacion,json=fechaActualizacion,proto3" json:"fecha_actualizacion,omitempty"`
	Activo             bool                   `protobuf:"varint,11,opt,name=activo,proto3" json:"activo,omitempty"`
	AreaActual         string                 `protobuf:"bytes,12,opt,name=area_actual,json=areaActual,proto3" json:"area_actual,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Expediente) Reset() {
	*x = Expediente{}
	mi := &file_expedientes_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expediente) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expediente) ProtoMessage() {}

func (x *Expediente) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expediente.ProtoReflect.Descriptor instead.
func (*Expediente) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{0}
}

func (x *Expediente) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expediente) GetCodigo() string {
	if x != nil {
		return x.Codigo
	}
	return ""
}

func (x *Expediente) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Expediente) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *Expediente) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Expediente) GetSolicitanteId() string {
	if x != nil {
		return x.SolicitanteId
	}
	return ""
}

func (x *Expediente) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Expediente) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

func (x *Expediente) GetFechaRegistro() string {
	if x != nil {
		return x.FechaRegistro
	}
	return ""
}

func (x *Expediente) GetFechaActualizacion() string {
	if x != nil {
		return x.FechaActualizacion
	}
	return ""
}

func (x *Expediente) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

func (x *Expediente) GetAreaActual() string {
	if x != nil {
		return x.AreaActual
	}
	return ""
}

type CreateExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          string                 `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Asunto        string                 `protobuf:"bytes,2,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Prioridad     string                 `protobuf:"bytes,4,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpedienteRequest) Reset() {
	*x = CreateExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpedienteRequest) ProtoMessage() {}

func (x *CreateExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpedienteRequest.ProtoReflect.Descriptor instead.
func (*CreateExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpedienteRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CreateExpedienteRequest) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *CreateExpedienteRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreateExpedienteRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

type CreateExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpedienteResponse) Reset() {
	*x = CreateExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpedienteResponse) ProtoMessage() {}

func (x *CreateExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpedienteResponse.ProtoReflect.Descriptor instead.
func (*CreateExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type GetExpedienteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Acepta el UUID interno o el codigo legible (EXP-2026-000001).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpedienteRequest) Reset() {
	*x = GetExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpedienteRequest) ProtoMessage() {}

func (x *GetExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpedienteRequest.ProtoReflect.Descriptor instead.
func (*GetExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpedienteResponse) Reset() {
	*x = GetExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpedienteResponse) ProtoMessage() {}

func (x *GetExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpedienteResponse.ProtoReflect.Descriptor instead.
func (*GetExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type ListExpedientesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Prioridad     string                 `protobuf:"bytes,2,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpedientesRequest) Reset() {
	*x = ListExpedientesRequest{}
	mi := &file_expedientes_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpedientesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpedientesRequest) ProtoMessage() {}

func (x *ListExpedientesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpedientesRequest.ProtoReflect.Descriptor instead.
func (*ListExpedientesRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListExpedientesRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ListExpedientesRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

func (x *ListExpedientesRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ListExpedientesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExpedientesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListExpedientesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expedientes   []*Expediente          `protobuf:"bytes,1,rep,name=expedientes,proto3" json:"expedientes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpedientesResponse) Reset() {
	*x = ListExpedientesResponse{}
	mi := &file_expedientes_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpedientesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpedientesResponse) ProtoMessage() {}

func (x *ListExpedientesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpedientesResponse.ProtoReflect.Descriptor instead.
func (*ListExpedientesResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListExpedientesResponse) GetExpedientes() []*Expediente {
	if x != nil {
		return x.Expedientes
	}
	return nil
}

func (x *ListExpedientesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Asunto        string                 `protobuf:"bytes,2,opt,name=asunto,proto3" json:"asunto,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Prioridad     string                 `protobuf:"bytes,4,opt,name=prioridad,proto3" json:"prioridad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpedienteRequest) Reset() {
	*x = UpdateExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpedienteRequest) ProtoMessage() {}

func (x *UpdateExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpedienteRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetAsunto() string {
	if x != nil {
		return x.Asunto
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *UpdateExpedienteRequest) GetPrioridad() string {
	if x != nil {
		return x.Prioridad
	}
	return ""
}

type UpdateExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpedienteResponse) Reset() {
	*x = UpdateExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpedienteResponse) ProtoMessage() {}

func (x *UpdateExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpedienteResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type ChangeEstadoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NuevoEstado   string                 `protobuf:"bytes,2,opt,name=nuevo_estado,json=nuevoEstado,proto3" json:"nuevo_estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEstadoRequest) Reset() {
	*x = ChangeEstadoRequest{}
	mi := &file_expedientes_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEstadoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEstadoRequest) ProtoMessage() {}

func (x *ChangeEstadoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEstadoRequest.ProtoReflect.Descriptor instead.
func (*ChangeEstadoRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeEstadoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeEstadoRequest) GetNuevoEstado() string {
	if x != nil {
		return x.NuevoEstado
	}
	return ""
}

type ChangeEstadoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEstadoResponse) Reset() {
	*x = ChangeEstadoResponse{}
	mi := &file_expedientes_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEstadoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEstadoResponse) ProtoMessage() {}

func (x *ChangeEstadoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEstadoResponse.ProtoReflect.Descriptor instead.
func (*ChangeEstadoResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeEstadoResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

type DeleteExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpedienteRequest) Reset() {
	*x = DeleteExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpedienteRequest) ProtoMessage() {}

func (x *DeleteExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpedienteRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpedienteResponse) Reset() {
	*x = DeleteExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpedienteResponse) ProtoMessage() {}

func (x *DeleteExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpedienteResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteExpedienteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateAreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAreaRequest) Reset() {
	*x = UpdateAreaRequest{}
	mi := &file_expedientes_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaRequest) ProtoMessage() {}

func (x *UpdateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAreaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAreaRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type UpdateAreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAreaResponse) Reset() {
	*x = UpdateAreaResponse{}
	mi := &file_expedientes_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaResponse) ProtoMessage() {}

func (x *UpdateAreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaResponse.ProtoReflect.Descriptor instead.
func (*UpdateAreaResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAreaResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

// DerivarExpediente (Etapa 3): operación de negocio real, distinta de
// UpdateArea genérico — valida que la transición de área esté confirmada
// para el tipo de trámite del expediente (ver internal/estados.CanDerivar)
// antes de moverlo. UpdateArea sigue existiendo tal cual para el resto de
// usos (administrativos, tipos genéricos) que no pasan por esta regla.
type DerivarExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AreaDestino   string                 `protobuf:"bytes,2,opt,name=area_destino,json=areaDestino,proto3" json:"area_destino,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DerivarExpedienteRequest) Reset() {
	*x = DerivarExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivarExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivarExpedienteRequest) ProtoMessage() {}

func (x *DerivarExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivarExpedienteRequest.ProtoReflect.Descriptor instead.
func (*DerivarExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{15}
}

func (x *DerivarExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DerivarExpedienteRequest) GetAreaDestino() string {
	if x != nil {
		return x.AreaDestino
	}
	return ""
}

type DerivarExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DerivarExpedienteResponse) Reset() {
	*x = DerivarExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivarExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivarExpedienteResponse) ProtoMessage() {}

func (x *DerivarExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivarExpedienteResponse.ProtoReflect.Descriptor instead.
func (*DerivarExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{16}
}

func (x *DerivarExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

// RechazarExpediente: exclusivo de F4. Lo ejecuta quien tiene actualmente
// el expediente (DIRECTOR o SUBDIRECTOR) para devolverlo a SECRETARIA con
// estado OBSERVADO, para que el solicitante corrija.
type RechazarExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Motivo        string                 `protobuf:"bytes,2,opt,name=motivo,proto3" json:"motivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechazarExpedienteRequest) Reset() {
	*x = RechazarExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechazarExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechazarExpedienteRequest) ProtoMessage() {}

func (x *RechazarExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechazarExpedienteRequest.ProtoReflect.Descriptor instead.
func (*RechazarExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{17}
}

func (x *RechazarExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RechazarExpedienteRequest) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

type RechazarExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechazarExpedienteResponse) Reset() {
	*x = RechazarExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechazarExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechazarExpedienteResponse) ProtoMessage() {}

func (x *RechazarExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechazarExpedienteResponse.ProtoReflect.Descriptor instead.
func (*RechazarExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{18}
}

func (x *RechazarExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

// CorregirExpediente: exclusivo del propio solicitante, sobre su propio
// expediente en estado OBSERVADO. Actualiza la descripción (la corrección)
// y reingresa a la revisión de Secretaría (vuelve a PENDIENTE).
type CorregirExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Descripcion   string                 `protobuf:"bytes,2,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorregirExpedienteRequest) Reset() {
	*x = CorregirExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorregirExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorregirExpedienteRequest) ProtoMessage() {}

func (x *CorregirExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorregirExpedienteRequest.ProtoReflect.Descriptor instead.
func (*CorregirExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{19}
}

func (x *CorregirExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CorregirExpedienteRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

type CorregirExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorregirExpedienteResponse) Reset() {
	*x = CorregirExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorregirExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorregirExpedienteResponse) ProtoMessage() {}

func (x *CorregirExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorregirExpedienteResponse.ProtoReflect.Descriptor instead.
func (*CorregirExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{20}
}

func (x *CorregirExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

// ResolverExpediente: exclusivo de F2, lo ejecuta Secretaría cuando ya
// tiene el documento final (verificado por el Gateway contra Documentos
// Service antes de llamar acá) y cierra el expediente como ATENDIDO.
type ResolverExpedienteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolverExpedienteRequest) Reset() {
	*x = ResolverExpedienteRequest{}
	mi := &file_expedientes_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverExpedienteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverExpedienteRequest) ProtoMessage() {}

func (x *ResolverExpedienteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverExpedienteRequest.ProtoReflect.Descriptor instead.
func (*ResolverExpedienteRequest) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{21}
}

func (x *ResolverExpedienteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolverExpedienteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expediente    *Expediente            `protobuf:"bytes,1,opt,name=expediente,proto3" json:"expediente,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolverExpedienteResponse) Reset() {
	*x = ResolverExpedienteResponse{}
	mi := &file_expedientes_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverExpedienteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverExpedienteResponse) ProtoMessage() {}

func (x *ResolverExpedienteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expedientes_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverExpedienteResponse.ProtoReflect.Descriptor instead.
func (*ResolverExpedienteResponse) Descriptor() ([]byte, []int) {
	return file_expedientes_service_proto_rawDescGZIP(), []int{22}
}

func (x *ResolverExpedienteResponse) GetExpediente() *Expediente {
	if x != nil {
		return x.Expediente
	}
	return nil
}

var File_expedientes_service_proto protoreflect.FileDescriptor

const file_expedientes_service_proto_rawDesc = "" +
	"\n" +
	"\x19expedientes_service.proto\x12\vexpedientes\"\xf0\x02\n" +
	"\n" +
	"Expediente\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\tR\x06codigo\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06asunto\x18\x04 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x05 \x01(\tR\vdescripcion\x12%\n" +
	"\x0esolicitante_id\x18\x06 \x01(\tR\rsolicitanteId\x12\x16\n" +
	"\x06estado\x18\a \x01(\tR\x06estado\x12\x1c\n" +
	"\tprioridad\x18\b \x01(\tR\tprioridad\x12%\n" +
	"\x0efecha_registro\x18\t \x01(\tR\rfechaRegistro\x12/\n" +
	"\x13fecha_actualizacion\x18\n" +
	" \x01(\tR\x12fechaActualizacion\x12\x16\n" +
	"\x06activo\x18\v \x01(\bR\x06activo\x12\x1f\n" +
	"\varea_actual\x18\f \x01(\tR\n" +
	"areaActual\"\x85\x01\n" +
	"\x17CreateExpedienteRequest\x12\x12\n" +
	"\x04tipo\x18\x01 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06asunto\x18\x02 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x1c\n" +
	"\tprioridad\x18\x04 \x01(\tR\tprioridad\"S\n" +
	"\x18CreateExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"&\n" +
	"\x14GetExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x15GetExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"\x93\x01\n" +
	"\x16ListExpedientesRequest\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12\x1c\n" +
	"\tprioridad\x18\x02 \x01(\tR\tprioridad\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"j\n" +
	"\x17ListExpedientesResponse\x129\n" +
	"\vexpedientes\x18\x01 \x03(\v2\x17.expedientes.ExpedienteR\vexpedientes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x81\x01\n" +
	"\x17UpdateExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06asunto\x18\x02 \x01(\tR\x06asunto\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x1c\n" +
	"\tprioridad\x18\x04 \x01(\tR\tprioridad\"S\n" +
	"\x18UpdateExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"H\n" +
	"\x13ChangeEstadoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fnuevo_estado\x18\x02 \x01(\tR\vnuevoEstado\"O\n" +
	"\x14ChangeEstadoResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\")\n" +
	"\x17DeleteExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteExpedienteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x11UpdateAreaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\"M\n" +
	"\x12UpdateAreaResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"M\n" +
	"\x18DerivarExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\farea_destino\x18\x02 \x01(\tR\vareaDestino\"T\n" +
	"\x19DerivarExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"C\n" +
	"\x19RechazarExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06motivo\x18\x02 \x01(\tR\x06motivo\"U\n" +
	"\x1aRechazarExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"M\n" +
	"\x19CorregirExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescripcion\x18\x02 \x01(\tR\vdescripcion\"U\n" +
	"\x1aCorregirExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente\"+\n" +
	"\x19ResolverExpedienteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x1aResolverExpedienteResponse\x127\n" +
	"\n" +
	"expediente\x18\x01 \x01(\v2\x17.expedientes.ExpedienteR\n" +
	"expediente2\xa3\b\n" +
	"\vExpedientes\x12_\n" +
	"\x10CreateExpediente\x12$.expedientes.CreateExpedienteRequest\x1a%.expedientes.CreateExpedienteResponse\x12V\n" +
	"\rGetExpediente\x12!.expedientes.GetExpedienteRequest\x1a\".expedientes.GetExpedienteResponse\x12\\\n" +
	"\x0fListExpedientes\x12#.expedientes.ListExpedientesRequest\x1a$.expedientes.ListExpedientesResponse\x12_\n" +
	"\x10UpdateExpediente\x12$.expedientes.UpdateExpedienteRequest\x1a%.expedientes.UpdateExpedienteResponse\x12S\n" +
	"\fChangeEstado\x12 .expedientes.ChangeEstadoRequest\x1a!.expedientes.ChangeEstadoResponse\x12_\n" +
	"\x10DeleteExpediente\x12$.expedientes.DeleteExpedienteRequest\x1a%.expedientes.DeleteExpedienteResponse\x12M\n" +
	"\n" +
	"UpdateArea\x12\x1e.expedientes.UpdateAreaRequest\x1a\x1f.expedientes.UpdateAreaResponse\x12b\n" +
	"\x11DerivarExpediente\x12%.expedientes.DerivarExpedienteRequest\x1a&.expedientes.DerivarExpedienteResponse\x12e\n" +
	"\x12RechazarExpediente\x12&.expedientes.RechazarExpedienteRequest\x1a'.expedientes.RechazarExpedienteResponse\x12e\n" +
	"\x12CorregirExpediente\x12&.expedientes.CorregirExpedienteRequest\x1a'.expedientes.CorregirExpedienteResponse\x12e\n" +
	"\x12ResolverExpediente\x12&.expedientes.ResolverExpedienteRequest\x1a'.expedientes.ResolverExpedienteResponseB\x0fZ\r./expedientesb\x06proto3"

var (
	file_expedientes_service_proto_rawDescOnce sync.Once
	file_expedientes_service_proto_rawDescData []byte
)

func file_expedientes_service_proto_rawDescGZIP() []byte {
	file_expedientes_service_proto_rawDescOnce.Do(func() {
		file_expedientes_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expedientes_service_proto_rawDesc), len(file_expedientes_service_proto_rawDesc)))
	})
	return file_expedientes_service_proto_rawDescData
}

var file_expedientes_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_expedientes_service_proto_goTypes = []any{
	(*Expediente)(nil),                 // 0: expedientes.Expediente
	(*CreateExpedienteRequest)(nil),    // 1: expedientes.CreateExpedienteRequest
	(*CreateExpedienteResponse)(nil),   // 2: expedientes.CreateExpedienteResponse
	(*GetExpedienteRequest)(nil),       // 3: expedientes.GetExpedienteRequest
	(*GetExpedienteResponse)(nil),      // 4: expedientes.GetExpedienteResponse
	(*ListExpedientesRequest)(nil),     // 5: expedientes.ListExpedientesRequest
	(*ListExpedientesResponse)(nil),    // 6: expedientes.ListExpedientesResponse
	(*UpdateExpedienteRequest)(nil),    // 7: expedientes.UpdateExpedienteRequest
	(*UpdateExpedienteResponse)(nil),   // 8: expedientes.UpdateExpedienteResponse
	(*ChangeEstadoRequest)(nil),        // 9: expedientes.ChangeEstadoRequest
	(*ChangeEstadoResponse)(nil),       // 10: expedientes.ChangeEstadoResponse
	(*DeleteExpedienteRequest)(nil),    // 11: expedientes.DeleteExpedienteRequest
	(*DeleteExpedienteResponse)(nil),   // 12: expedientes.DeleteExpedienteResponse
	(*UpdateAreaRequest)(nil),          // 13: expedientes.UpdateAreaRequest
	(*UpdateAreaResponse)(nil),         // 14: expedientes.UpdateAreaResponse
	(*DerivarExpedienteRequest)(nil),   // 15: expedientes.DerivarExpedienteRequest
	(*DerivarExpedienteResponse)(nil),  // 16: expedientes.DerivarExpedienteResponse
	(*RechazarExpedienteRequest)(nil),  // 17: expedientes.RechazarExpedienteRequest
	(*RechazarExpedienteResponse)(nil), // 18: expedientes.RechazarExpedienteResponse
	(*CorregirExpedienteRequest)(nil),  // 19: expedientes.CorregirExpedienteRequest
	(*CorregirExpedienteResponse)(nil), // 20: expedientes.CorregirExpedienteResponse
	(*ResolverExpedienteRequest)(nil),  // 21: expedientes.ResolverExpedienteRequest
	(*ResolverExpedienteResponse)(nil), // 22: expedientes.ResolverExpedienteResponse
}
var file_expedientes_service_proto_depIdxs = []int32{
	0,  // 0: expedientes.CreateExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 1: expedientes.GetExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 2: expedientes.ListExpedientesResponse.expedientes:type_name -> expedientes.Expediente
	0,  // 3: expedientes.UpdateExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 4: expedientes.ChangeEstadoResponse.expediente:type_name -> expedientes.Expediente
	0,  // 5: expedientes.UpdateAreaResponse.expediente:type_name -> expedientes.Expediente
	0,  // 6: expedientes.DerivarExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 7: expedientes.RechazarExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 8: expedientes.CorregirExpedienteResponse.expediente:type_name -> expedientes.Expediente
	0,  // 9: expedientes.ResolverExpedienteResponse.expediente:type_name -> expedientes.Expediente
	1,  // 10: expedientes.Expedientes.CreateExpediente:input_type -> expedientes.CreateExpedienteRequest
	3,  // 11: expedientes.Expedientes.GetExpediente:input_type -> expedientes.GetExpedienteRequest
	5,  // 12: expedientes.Expedientes.ListExpedientes:input_type -> expedientes.ListExpedientesRequest
	7,  // 13: expedientes.Expedientes.UpdateExpediente:input_type -> expedientes.UpdateExpedienteRequest
	9,  // 14: expedientes.Expedientes.ChangeEstado:input_type -> expedientes.ChangeEstadoRequest
	11, // 15: expedientes.Expedientes.DeleteExpediente:input_type -> expedientes.DeleteExpedienteRequest
	13, // 16: expedientes.Expedientes.UpdateArea:input_type -> expedientes.UpdateAreaRequest
	15, // 17: expedientes.Expedientes.DerivarExpediente:input_type -> expedientes.DerivarExpedienteRequest
	17, // 18: expedientes.Expedientes.RechazarExpediente:input_type -> expedientes.RechazarExpedienteRequest
	19, // 19: expedientes.Expedientes.CorregirExpediente:input_type -> expedientes.CorregirExpedienteRequest
	21, // 20: expedientes.Expedientes.ResolverExpediente:input_type -> expedientes.ResolverExpedienteRequest
	2,  // 21: expedientes.Expedientes.CreateExpediente:output_type -> expedientes.CreateExpedienteResponse
	4,  // 22: expedientes.Expedientes.GetExpediente:output_type -> expedientes.GetExpedienteResponse
	6,  // 23: expedientes.Expedientes.ListExpedientes:output_type -> expedientes.ListExpedientesResponse
	8,  // 24: expedientes.Expedientes.UpdateExpediente:output_type -> expedientes.UpdateExpedienteResponse
	10, // 25: expedientes.Expedientes.ChangeEstado:output_type -> expedientes.ChangeEstadoResponse
	12, // 26: expedientes.Expedientes.DeleteExpediente:output_type -> expedientes.DeleteExpedienteResponse
	14, // 27: expedientes.Expedientes.UpdateArea:output_type -> expedientes.UpdateAreaResponse
	16, // 28: expedientes.Expedientes.DerivarExpediente:output_type -> expedientes.DerivarExpedienteResponse
	18, // 29: expedientes.Expedientes.RechazarExpediente:output_type -> expedientes.RechazarExpedienteResponse
	20, // 30: expedientes.Expedientes.CorregirExpediente:output_type -> expedientes.CorregirExpedienteResponse
	22, // 31: expedientes.Expedientes.ResolverExpediente:output_type -> expedientes.ResolverExpedienteResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_expedientes_service_proto_init() }
func file_expedientes_service_proto_init() {
	if File_expedientes_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expedientes_service_proto_rawDesc), len(file_expedientes_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expedientes_service_proto_goTypes,
		DependencyIndexes: file_expedientes_service_proto_depIdxs,
		MessageInfos:      file_expedientes_service_proto_msgTypes,
	}.Build()
	File_expedientes_service_proto = out.File
	file_expedientes_service_proto_goTypes = nil
	file_expedientes_service_proto_depIdxs = nil
}
