// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: documentos_service.proto

package documentos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Documento struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpedienteId  string                 `protobuf:"bytes,2,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	TipoDocumento string                 `protobuf:"bytes,4,opt,name=tipo_documento,json=tipoDocumento,proto3" json:"tipo_documento,omitempty"`
	Extension     string                 `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	TamanoBytes   int64                  `protobuf:"varint,6,opt,name=tamano_bytes,json=tamanoBytes,proto3" json:"tamano_bytes,omitempty"`
	SubidoPor     string                 `protobuf:"bytes,7,opt,name=subido_por,json=subidoPor,proto3" json:"subido_por,omitempty"`
	Estado        string                 `protobuf:"bytes,8,opt,name=estado,proto3" json:"estado,omitempty"`
	FechaRegistro string                 `protobuf:"bytes,9,opt,name=fecha_registro,json=fechaRegistro,proto3" json:"fecha_registro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Documento) Reset() {
	*x = Documento{}
	mi := &file_documentos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Documento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Documento) ProtoMessage() {}

func (x *Documento) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Documento.ProtoReflect.Descriptor instead.
func (*Documento) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{0}
}

func (x *Documento) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Documento) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

func (x *Documento) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Documento) GetTipoDocumento() string {
	if x != nil {
		return x.TipoDocumento
	}
	return ""
}

func (x *Documento) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *Documento) GetTamanoBytes() int64 {
	if x != nil {
		return x.TamanoBytes
	}
	return 0
}

func (x *Documento) GetSubidoPor() string {
	if x != nil {
		return x.SubidoPor
	}
	return ""
}

func (x *Documento) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Documento) GetFechaRegistro() string {
	if x != nil {
		return x.FechaRegistro
	}
	return ""
}

type UploadDocumentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpedienteId  string                 `protobuf:"bytes,1,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	TipoDocumento string                 `protobuf:"bytes,3,opt,name=tipo_documento,json=tipoDocumento,proto3" json:"tipo_documento,omitempty"`
	Extension     string                 `protobuf:"bytes,4,opt,name=extension,proto3" json:"extension,omitempty"`
	Contenido     []byte                 `protobuf:"bytes,5,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentoRequest) Reset() {
	*x = UploadDocumentoRequest{}
	mi := &file_documentos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentoRequest) ProtoMessage() {}

func (x *UploadDocumentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentoRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentoRequest) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentoRequest) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

func (x *UploadDocumentoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *UploadDocumentoRequest) GetTipoDocumento() string {
	if x != nil {
		return x.TipoDocumento
	}
	return ""
}

func (x *UploadDocumentoRequest) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *UploadDocumentoRequest) GetContenido() []byte {
	if x != nil {
		return x.Contenido
	}
	return nil
}

type UploadDocumentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documento     *Documento             `protobuf:"bytes,1,opt,name=documento,proto3" json:"documento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentoResponse) Reset() {
	*x = UploadDocumentoResponse{}
	mi := &file_documentos_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentoResponse) ProtoMessage() {}

func (x *UploadDocumentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentoResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentoResponse) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDocumentoResponse) GetDocumento() *Documento {
	if x != nil {
		return x.Documento
	}
	return nil
}

type GetDocumentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentoRequest) Reset() {
	*x = GetDocumentoRequest{}
	mi := &file_documentos_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentoRequest) ProtoMessage() {}

func (x *GetDocumentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentoRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentoRequest) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDocumentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documento     *Documento             `protobuf:"bytes,1,opt,name=documento,proto3" json:"documento,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentoResponse) Reset() {
	*x = GetDocumentoResponse{}
	mi := &file_documentos_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentoResponse) ProtoMessage() {}

func (x *GetDocumentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentoResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentoResponse) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentoResponse) GetDocumento() *Documento {
	if x != nil {
		return x.Documento
	}
	return nil
}

type DownloadDocumentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentoRequest) Reset() {
	*x = DownloadDocumentoRequest{}
	mi := &file_documentos_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentoRequest) ProtoMessage() {}

func (x *DownloadDocumentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentoRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentoRequest) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadDocumentoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadDocumentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documento     *Documento             `protobuf:"bytes,1,opt,name=documento,proto3" json:"documento,omitempty"`
	Contenido     []byte                 `protobuf:"bytes,2,opt,name=contenido,proto3" json:"contenido,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentoResponse) Reset() {
	*x = DownloadDocumentoResponse{}
	mi := &file_documentos_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentoResponse) ProtoMessage() {}

func (x *DownloadDocumentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentoResponse.ProtoReflect.Descriptor instead.
func (*DownloadDocumentoResponse) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadDocumentoResponse) GetDocumento() *Documento {
	if x != nil {
		return x.Documento
	}
	return nil
}

func (x *DownloadDocumentoResponse) GetContenido() []byte {
	if x != nil {
		return x.Contenido
	}
	return nil
}

type ListDocumentosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpedienteId  string                 `protobuf:"bytes,1,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentosRequest) Reset() {
	*x = ListDocumentosRequest{}
	mi := &file_documentos_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentosRequest) ProtoMessage() {}

func (x *ListDocumentosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentosRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentosRequest) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListDocumentosRequest) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

type ListDocumentosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documentos    []*Documento           `protobuf:"bytes,1,rep,name=documentos,proto3" json:"documentos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentosResponse) Reset() {
	*x = ListDocumentosResponse{}
	mi := &file_documentos_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentosResponse) ProtoMessage() {}

func (x *ListDocumentosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentosResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentosResponse) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListDocumentosResponse) GetDocumentos() []*Documento {
	if x != nil {
		return x.Documentos
	}
	return nil
}

type DeleteDocumentoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentoRequest) Reset() {
	*x = DeleteDocumentoRequest{}
	mi := &file_documentos_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentoRequest) ProtoMessage() {}

func (x *DeleteDocumentoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentoRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentoRequest) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDocumentoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentoResponse) Reset() {
	*x = DeleteDocumentoResponse{}
	mi := &file_documentos_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentoResponse) ProtoMessage() {}

func (x *DeleteDocumentoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentos_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentoResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentoResponse) Descriptor() ([]byte, []int) {
	return file_documentos_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDocumentoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_documentos_service_proto protoreflect.FileDescriptor

const file_documentos_service_proto_rawDesc = "" +
	"\n" +
	"\x18documentos_service.proto\x12\n" +
	"documentos\"\x9e\x02\n" +
	"\tDocumento\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rexpediente_id\x18\x02 \x01(\tR\fexpedienteId\x12\x16\n" +
	"\x06nombre\x18\x03 \x01(\tR\x06nombre\x12%\n" +
	"\x0etipo_documento\x18\x04 \x01(\tR\rtipoDocumento\x12\x1c\n" +
	"\textension\x18\x05 \x01(\tR\textension\x12!\n" +
	"\ftamano_bytes\x18\x06 \x01(\x03R\vtamanoBytes\x12\x1d\n" +
	"\n" +
	"subido_por\x18\a \x01(\tR\tsubidoPor\x12\x16\n" +
	"\x06estado\x18\b \x01(\tR\x06estado\x12%\n" +
	"\x0efecha_registro\x18\t \x01(\tR\rfechaRegistro\"\xb8\x01\n" +
	"\x16UploadDocumentoRequest\x12#\n" +
	"\rexpediente_id\x18\x01 \x01(\tR\fexpedienteId\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12%\n" +
	"\x0etipo_documento\x18\x03 \x01(\tR\rtipoDocumento\x12\x1c\n" +
	"\textension\x18\x04 \x01(\tR\textension\x12\x1c\n" +
	"\tcontenido\x18\x05 \x01(\fR\tcontenido\"N\n" +
	"\x17UploadDocumentoResponse\x123\n" +
	"\tdocumento\x18\x01 \x01(\v2\x15.documentos.DocumentoR\tdocumento\"%\n" +
	"\x13GetDocumentoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x14GetDocumentoResponse\x123\n" +
	"\tdocumento\x18\x01 \x01(\v2\x15.documentos.DocumentoR\tdocumento\"*\n" +
	"\x18DownloadDocumentoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x19DownloadDocumentoResponse\x123\n" +
	"\tdocumento\x18\x01 \x01(\v2\x15.documentos.DocumentoR\tdocumento\x12\x1c\n" +
	"\tcontenido\x18\x02 \x01(\fR\tcontenido\"<\n" +
	"\x15ListDocumentosRequest\x12#\n" +
	"\rexpediente_id\x18\x01 \x01(\tR\fexpedienteId\"O\n" +
	"\x16ListDocumentosResponse\x125\n" +
	"\n" +
	"documentos\x18\x01 \x03(\v2\x15.documentos.DocumentoR\n" +
	"documentos\"(\n" +
	"\x16DeleteDocumentoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17DeleteDocumentoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd2\x03\n" +
	"\n" +
	"Documentos\x12Z\n" +
	"\x0fUploadDocumento\x12\".documentos.UploadDocumentoRequest\x1a#.documentos.UploadDocumentoResponse\x12Q\n" +
	"\fGetDocumento\x12\x1f.documentos.GetDocumentoRequest\x1a .documentos.GetDocumentoResponse\x12`\n" +
	"\x11DownloadDocumento\x12$.documentos.DownloadDocumentoRequest\x1a%.documentos.DownloadDocumentoResponse\x12W\n" +
	"\x0eListDocumentos\x12!.documentos.ListDocumentosRequest\x1a\".documentos.ListDocumentosResponse\x12Z\n" +
	"\x0fDeleteDocumento\x12\".documentos.DeleteDocumentoRequest\x1a#.documentos.DeleteDocumentoResponseB\x0eZ\f./documentosb\x06proto3"

var (
	file_documentos_service_proto_rawDescOnce sync.Once
	file_documentos_service_proto_rawDescData []byte
)

func file_documentos_service_proto_rawDescGZIP() []byte {
	file_documentos_service_proto_rawDescOnce.Do(func() {
		file_documentos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_documentos_service_proto_rawDesc), len(file_documentos_service_proto_rawDesc)))
	})
	return file_documentos_service_proto_rawDescData
}

var file_documentos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_documentos_service_proto_goTypes = []any{
	(*Documento)(nil),                 // 0: documentos.Documento
	(*UploadDocumentoRequest)(nil),    // 1: documentos.UploadDocumentoRequest
	(*UploadDocumentoResponse)(nil),   // 2: documentos.UploadDocumentoResponse
	(*GetDocumentoRequest)(nil),       // 3: documentos.GetDocumentoRequest
	(*GetDocumentoResponse)(nil),      // 4: documentos.GetDocumentoResponse
	(*DownloadDocumentoRequest)(nil),  // 5: documentos.DownloadDocumentoRequest
	(*DownloadDocumentoResponse)(nil), // 6: documentos.DownloadDocumentoResponse
	(*ListDocumentosRequest)(nil),     // 7: documentos.ListDocumentosRequest
	(*ListDocumentosResponse)(nil),    // 8: documentos.ListDocumentosResponse
	(*DeleteDocumentoRequest)(nil),    // 9: documentos.DeleteDocumentoRequest
	(*DeleteDocumentoResponse)(nil),   // 10: documentos.DeleteDocumentoResponse
}
var file_documentos_service_proto_depIdxs = []int32{
	0,  // 0: documentos.UploadDocumentoResponse.documento:type_name -> documentos.Documento
	0,  // 1: documentos.GetDocumentoResponse.documento:type_name -> documentos.Documento
	0,  // 2: documentos.DownloadDocumentoResponse.documento:type_name -> documentos.Documento
	0,  // 3: documentos.ListDocumentosResponse.documentos:type_name -> documentos.Documento
	1,  // 4: documentos.Documentos.UploadDocumento:input_type -> documentos.UploadDocumentoRequest
	3,  // 5: documentos.Documentos.GetDocumento:input_type -> documentos.GetDocumentoRequest
	5,  // 6: documentos.Documentos.DownloadDocumento:input_type -> documentos.DownloadDocumentoRequest
	7,  // 7: documentos.Documentos.ListDocumentos:input_type -> documentos.ListDocumentosRequest
	9,  // 8: documentos.Documentos.DeleteDocumento:input_type -> documentos.DeleteDocumentoRequest
	2,  // 9: documentos.Documentos.UploadDocumento:output_type -> documentos.UploadDocumentoResponse
	4,  // 10: documentos.Documentos.GetDocumento:output_type -> documentos.GetDocumentoResponse
	6,  // 11: documentos.Documentos.DownloadDocumento:output_type -> documentos.DownloadDocumentoResponse
	8,  // 12: documentos.Documentos.ListDocumentos:output_type -> documentos.ListDocumentosResponse
	10, // 13: documentos.Documentos.DeleteDocumento:output_type -> documentos.DeleteDocumentoResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_documentos_service_proto_init() }
func file_documentos_service_proto_init() {
	if File_documentos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_documentos_service_proto_rawDesc), len(file_documentos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_documentos_service_proto_goTypes,
		DependencyIndexes: file_documentos_service_proto_depIdxs,
		MessageInfos:      file_documentos_service_proto_msgTypes,
	}.Build()
	File_documentos_service_proto = out.File
	file_documentos_service_proto_goTypes = nil
	file_documentos_service_proto_depIdxs = nil
}
