// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: documentos_service.proto

package documentos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Documentos_UploadDocumento_FullMethodName   = "/documentos.Documentos/UploadDocumento"
	Documentos_GetDocumento_FullMethodName      = "/documentos.Documentos/GetDocumento"
	Documentos_DownloadDocumento_FullMethodName = "/documentos.Documentos/DownloadDocumento"
	Documentos_ListDocumentos_FullMethodName    = "/documentos.Documentos/ListDocumentos"
	Documentos_DeleteDocumento_FullMethodName   = "/documentos.Documentos/DeleteDocumento"
)

// DocumentosClient is the client API for Documentos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentosClient interface {
	UploadDocumento(ctx context.Context, in *UploadDocumentoRequest, opts ...grpc.CallOption) (*UploadDocumentoResponse, error)
	GetDocumento(ctx context.Context, in *GetDocumentoRequest, opts ...grpc.CallOption) (*GetDocumentoResponse, error)
	DownloadDocumento(ctx context.Context, in *DownloadDocumentoRequest, opts ...grpc.CallOption) (*DownloadDocumentoResponse, error)
	ListDocumentos(ctx context.Context, in *ListDocumentosRequest, opts ...grpc.CallOption) (*ListDocumentosResponse, error)
	DeleteDocumento(ctx context.Context, in *DeleteDocumentoRequest, opts ...grpc.CallOption) (*DeleteDocumentoResponse, error)
}

type documentosClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentosClient(cc grpc.ClientConnInterface) DocumentosClient {
	return &documentosClient{cc}
}

func (c *documentosClient) UploadDocumento(ctx context.Context, in *UploadDocumentoRequest, opts ...grpc.CallOption) (*UploadDocumentoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocumentoResponse)
	err := c.cc.Invoke(ctx, Documentos_UploadDocumento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentosClient) GetDocumento(ctx context.Context, in *GetDocumentoRequest, opts ...grpc.CallOption) (*GetDocumentoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentoResponse)
	err := c.cc.Invoke(ctx, Documentos_GetDocumento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentosClient) DownloadDocumento(ctx context.Context, in *DownloadDocumentoRequest, opts ...grpc.CallOption) (*DownloadDocumentoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadDocumentoResponse)
	err := c.cc.Invoke(ctx, Documentos_DownloadDocumento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentosClient) ListDocumentos(ctx context.Context, in *ListDocumentosRequest, opts ...grpc.CallOption) (*ListDocumentosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentosResponse)
	err := c.cc.Invoke(ctx, Documentos_ListDocumentos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentosClient) DeleteDocumento(ctx context.Context, in *DeleteDocumentoRequest, opts ...grpc.CallOption) (*DeleteDocumentoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentoResponse)
	err := c.cc.Invoke(ctx, Documentos_DeleteDocumento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentosServer is the server API for Documentos service.
// All implementations must embed UnimplementedDocumentosServer
// for forward compatibility.
type DocumentosServer interface {
	UploadDocumento(context.Context, *UploadDocumentoRequest) (*UploadDocumentoResponse, error)
	GetDocumento(context.Context, *GetDocumentoRequest) (*GetDocumentoResponse, error)
	DownloadDocumento(context.Context, *DownloadDocumentoRequest) (*DownloadDocumentoResponse, error)
	ListDocumentos(context.Context, *ListDocumentosRequest) (*ListDocumentosResponse, error)
	DeleteDocumento(context.Context, *DeleteDocumentoRequest) (*DeleteDocumentoResponse, error)
	mustEmbedUnimplementedDocumentosServer()
}

// UnimplementedDocumentosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentosServer struct{}

func (UnimplementedDocumentosServer) UploadDocumento(context.Context, *UploadDocumentoRequest) (*UploadDocumentoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadDocumento not implemented")
}
func (UnimplementedDocumentosServer) GetDocumento(context.Context, *GetDocumentoRequest) (*GetDocumentoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumento not implemented")
}
func (UnimplementedDocumentosServer) DownloadDocumento(context.Context, *DownloadDocumentoRequest) (*DownloadDocumentoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadDocumento not implemented")
}
func (UnimplementedDocumentosServer) ListDocumentos(context.Context, *ListDocumentosRequest) (*ListDocumentosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocumentos not implemented")
}
func (UnimplementedDocumentosServer) DeleteDocumento(context.Context, *DeleteDocumentoRequest) (*DeleteDocumentoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocumento not implemented")
}
func (UnimplementedDocumentosServer) mustEmbedUnimplementedDocumentosServer() {}
func (UnimplementedDocumentosServer) testEmbeddedByValue()                    {}

// UnsafeDocumentosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentosServer will
// result in compilation errors.
type UnsafeDocumentosServer interface {
	mustEmbedUnimplementedDocumentosServer()
}

func RegisterDocumentosServer(s grpc.ServiceRegistrar, srv DocumentosServer) {
	// If the following call panics, it indicates UnimplementedDocumentosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Documentos_ServiceDesc, srv)
}

func _Documentos_UploadDocumento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocumentoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentosServer).UploadDocumento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documentos_UploadDocumento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentosServer).UploadDocumento(ctx, req.(*UploadDocumentoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentos_GetDocumento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentosServer).GetDocumento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documentos_GetDocumento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentosServer).GetDocumento(ctx, req.(*GetDocumentoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentos_DownloadDocumento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadDocumentoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentosServer).DownloadDocumento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documentos_DownloadDocumento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentosServer).DownloadDocumento(ctx, req.(*DownloadDocumentoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentos_ListDocumentos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentosServer).ListDocumentos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documentos_ListDocumentos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentosServer).ListDocumentos(ctx, req.(*ListDocumentosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documentos_DeleteDocumento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentosServer).DeleteDocumento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documentos_DeleteDocumento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentosServer).DeleteDocumento(ctx, req.(*DeleteDocumentoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Documentos_ServiceDesc is the grpc.ServiceDesc for Documentos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Documentos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "documentos.Documentos",
	HandlerType: (*DocumentosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadDocumento",
			Handler:    _Documentos_UploadDocumento_Handler,
		},
		{
			MethodName: "GetDocumento",
			Handler:    _Documentos_GetDocumento_Handler,
		},
		{
			MethodName: "DownloadDocumento",
			Handler:    _Documentos_DownloadDocumento_Handler,
		},
		{
			MethodName: "ListDocumentos",
			Handler:    _Documentos_ListDocumentos_Handler,
		},
		{
			MethodName: "DeleteDocumento",
			Handler:    _Documentos_DeleteDocumento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "documentos_service.proto",
}
