// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: usuarios_service.proto

package usuarios

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Perfil completo. Contiene datos personales: solo debe entregarse a quien
// esté autorizado (ver internal/authorization).
type Usuario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombres       string                 `protobuf:"bytes,2,opt,name=nombres,proto3" json:"nombres,omitempty"`
	Apellidos     string                 `protobuf:"bytes,3,opt,name=apellidos,proto3" json:"apellidos,omitempty"`
	Dni           string                 `protobuf:"bytes,4,opt,name=dni,proto3" json:"dni,omitempty"`
	Telefono      string                 `protobuf:"bytes,5,opt,name=telefono,proto3" json:"telefono,omitempty"`
	Correo        string                 `protobuf:"bytes,6,opt,name=correo,proto3" json:"correo,omitempty"`
	Direccion     string                 `protobuf:"bytes,7,opt,name=direccion,proto3" json:"direccion,omitempty"`
	TipoUsuario   string                 `protobuf:"bytes,8,opt,name=tipo_usuario,json=tipoUsuario,proto3" json:"tipo_usuario,omitempty"`
	Activo        bool                   `protobuf:"varint,9,opt,name=activo,proto3" json:"activo,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usuario) Reset() {
	*x = Usuario{}
	mi := &file_usuarios_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuario) ProtoMessage() {}

func (x *Usuario) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuario.ProtoReflect.Descriptor instead.
func (*Usuario) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{0}
}

func (x *Usuario) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Usuario) GetNombres() string {
	if x != nil {
		return x.Nombres
	}
	return ""
}

func (x *Usuario) GetApellidos() string {
	if x != nil {
		return x.Apellidos
	}
	return ""
}

func (x *Usuario) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

func (x *Usuario) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *Usuario) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *Usuario) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *Usuario) GetTipoUsuario() string {
	if x != nil {
		return x.TipoUsuario
	}
	return ""
}

func (x *Usuario) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

func (x *Usuario) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Usuario) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Proyección mínima pensada para resolver identificadores en otros módulos
// (Expedientes, Derivaciones, Seguimiento). No incluye teléfono, correo
// ni dirección. El dni solo se completa cuando quien consulta está
// autorizado a ver datos personales (personal interno o el propio usuario);
// para el resto viaja vacío.
type UsuarioBasic struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombres        string                 `protobuf:"bytes,2,opt,name=nombres,proto3" json:"nombres,omitempty"`
	Apellidos      string                 `protobuf:"bytes,3,opt,name=apellidos,proto3" json:"apellidos,omitempty"`
	NombreCompleto string                 `protobuf:"bytes,4,opt,name=nombre_completo,json=nombreCompleto,proto3" json:"nombre_completo,omitempty"`
	TipoUsuario    string                 `protobuf:"bytes,5,opt,name=tipo_usuario,json=tipoUsuario,proto3" json:"tipo_usuario,omitempty"`
	Dni            string                 `protobuf:"bytes,6,opt,name=dni,proto3" json:"dni,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsuarioBasic) Reset() {
	*x = UsuarioBasic{}
	mi := &file_usuarios_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsuarioBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioBasic) ProtoMessage() {}

func (x *UsuarioBasic) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioBasic.ProtoReflect.Descriptor instead.
func (*UsuarioBasic) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{1}
}

func (x *UsuarioBasic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UsuarioBasic) GetNombres() string {
	if x != nil {
		return x.Nombres
	}
	return ""
}

func (x *UsuarioBasic) GetApellidos() string {
	if x != nil {
		return x.Apellidos
	}
	return ""
}

func (x *UsuarioBasic) GetNombreCompleto() string {
	if x != nil {
		return x.NombreCompleto
	}
	return ""
}

func (x *UsuarioBasic) GetTipoUsuario() string {
	if x != nil {
		return x.TipoUsuario
	}
	return ""
}

func (x *UsuarioBasic) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

type GetUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuarioRequest) Reset() {
	*x = GetUsuarioRequest{}
	mi := &file_usuarios_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuarioRequest) ProtoMessage() {}

func (x *GetUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuarioRequest.ProtoReflect.Descriptor instead.
func (*GetUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsuarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuario       *Usuario               `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuarioResponse) Reset() {
	*x = GetUsuarioResponse{}
	mi := &file_usuarios_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuarioResponse) ProtoMessage() {}

func (x *GetUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuarioResponse.ProtoReflect.Descriptor instead.
func (*GetUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsuarioResponse) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

type GetUsuarioBasicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuarioBasicRequest) Reset() {
	*x = GetUsuarioBasicRequest{}
	mi := &file_usuarios_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuarioBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuarioBasicRequest) ProtoMessage() {}

func (x *GetUsuarioBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuarioBasicRequest.ProtoReflect.Descriptor instead.
func (*GetUsuarioBasicRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsuarioBasicRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUsuarioBasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuario       *UsuarioBasic          `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuarioBasicResponse) Reset() {
	*x = GetUsuarioBasicResponse{}
	mi := &file_usuarios_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuarioBasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuarioBasicResponse) ProtoMessage() {}

func (x *GetUsuarioBasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuarioBasicResponse.ProtoReflect.Descriptor instead.
func (*GetUsuarioBasicResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsuarioBasicResponse) GetUsuario() *UsuarioBasic {
	if x != nil {
		return x.Usuario
	}
	return nil
}

// Resolución por lote: evita N consultas cuando el Dashboard muestra una
// lista de expedientes de distintos solicitantes.
type GetUsuariosBasicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuariosBasicRequest) Reset() {
	*x = GetUsuariosBasicRequest{}
	mi := &file_usuarios_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuariosBasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuariosBasicRequest) ProtoMessage() {}

func (x *GetUsuariosBasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuariosBasicRequest.ProtoReflect.Descriptor instead.
func (*GetUsuariosBasicRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsuariosBasicRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsuariosBasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuarios      []*UsuarioBasic        `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsuariosBasicResponse) Reset() {
	*x = GetUsuariosBasicResponse{}
	mi := &file_usuarios_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsuariosBasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsuariosBasicResponse) ProtoMessage() {}

func (x *GetUsuariosBasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsuariosBasicResponse.ProtoReflect.Descriptor instead.
func (*GetUsuariosBasicResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsuariosBasicResponse) GetUsuarios() []*UsuarioBasic {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type ListUsuariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TipoUsuario   string                 `protobuf:"bytes,1,opt,name=tipo_usuario,json=tipoUsuario,proto3" json:"tipo_usuario,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsuariosRequest) Reset() {
	*x = ListUsuariosRequest{}
	mi := &file_usuarios_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsuariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsuariosRequest) ProtoMessage() {}

func (x *ListUsuariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsuariosRequest.ProtoReflect.Descriptor instead.
func (*ListUsuariosRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsuariosRequest) GetTipoUsuario() string {
	if x != nil {
		return x.TipoUsuario
	}
	return ""
}

func (x *ListUsuariosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsuariosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsuariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuarios      []*Usuario             `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsuariosResponse) Reset() {
	*x = ListUsuariosResponse{}
	mi := &file_usuarios_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsuariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsuariosResponse) ProtoMessage() {}

func (x *ListUsuariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsuariosResponse.ProtoReflect.Descriptor instead.
func (*ListUsuariosResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListUsuariosResponse) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

func (x *ListUsuariosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchUsuariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TipoUsuario   string                 `protobuf:"bytes,2,opt,name=tipo_usuario,json=tipoUsuario,proto3" json:"tipo_usuario,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsuariosRequest) Reset() {
	*x = SearchUsuariosRequest{}
	mi := &file_usuarios_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsuariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsuariosRequest) ProtoMessage() {}

func (x *SearchUsuariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsuariosRequest.ProtoReflect.Descriptor instead.
func (*SearchUsuariosRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUsuariosRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsuariosRequest) GetTipoUsuario() string {
	if x != nil {
		return x.TipoUsuario
	}
	return ""
}

func (x *SearchUsuariosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsuariosRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsuariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuarios      []*Usuario             `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsuariosResponse) Reset() {
	*x = SearchUsuariosResponse{}
	mi := &file_usuarios_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsuariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsuariosResponse) ProtoMessage() {}

func (x *SearchUsuariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsuariosResponse.ProtoReflect.Descriptor instead.
func (*SearchUsuariosResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchUsuariosResponse) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

func (x *SearchUsuariosResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// UpsertUsuario permite crear/actualizar el perfil asociado a un usuario ya
// existente en Auth. El id NO se genera aquí: debe ser el mismo UUID que
// Auth Service asignó al usuario.
type UpsertUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombres       string                 `protobuf:"bytes,2,opt,name=nombres,proto3" json:"nombres,omitempty"`
	Apellidos     string                 `protobuf:"bytes,3,opt,name=apellidos,proto3" json:"apellidos,omitempty"`
	Dni           string                 `protobuf:"bytes,4,opt,name=dni,proto3" json:"dni,omitempty"`
	Telefono      string                 `protobuf:"bytes,5,opt,name=telefono,proto3" json:"telefono,omitempty"`
	Correo        string                 `protobuf:"bytes,6,opt,name=correo,proto3" json:"correo,omitempty"`
	Direccion     string                 `protobuf:"bytes,7,opt,name=direccion,proto3" json:"direccion,omitempty"`
	TipoUsuario   string                 `protobuf:"bytes,8,opt,name=tipo_usuario,json=tipoUsuario,proto3" json:"tipo_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUsuarioRequest) Reset() {
	*x = UpsertUsuarioRequest{}
	mi := &file_usuarios_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUsuarioRequest) ProtoMessage() {}

func (x *UpsertUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUsuarioRequest.ProtoReflect.Descriptor instead.
func (*UpsertUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertUsuarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetNombres() string {
	if x != nil {
		return x.Nombres
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetApellidos() string {
	if x != nil {
		return x.Apellidos
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetDni() string {
	if x != nil {
		return x.Dni
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *UpsertUsuarioRequest) GetTipoUsuario() string {
	if x != nil {
		return x.TipoUsuario
	}
	return ""
}

type UpsertUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuario       *Usuario               `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUsuarioResponse) Reset() {
	*x = UpsertUsuarioResponse{}
	mi := &file_usuarios_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUsuarioResponse) ProtoMessage() {}

func (x *UpsertUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUsuarioResponse.ProtoReflect.Descriptor instead.
func (*UpsertUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertUsuarioResponse) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

// UpdateMyProfile (Paso 22E): edición del PROPIO perfil por el usuario
// autenticado. A propósito NO incluye id/user_id: la identidad se obtiene
// exclusivamente del contexto autenticado (JWT), nunca de un campo del
// request — evita cualquier IDOR. Solo cubre los 3 campos de contacto que
// el propio usuario puede tocar sobre sí mismo (ver Paso 22D/22B):
// nombres, apellidos, DNI, tipo_usuario y activo permanecen fuera de este
// RPC (edición administrativa, no implementada todavía).
type UpdateMyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telefono      string                 `protobuf:"bytes,1,opt,name=telefono,proto3" json:"telefono,omitempty"`
	Correo        string                 `protobuf:"bytes,2,opt,name=correo,proto3" json:"correo,omitempty"`
	Direccion     string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileRequest) Reset() {
	*x = UpdateMyProfileRequest{}
	mi := &file_usuarios_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileRequest) ProtoMessage() {}

func (x *UpdateMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMyProfileRequest) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *UpdateMyProfileRequest) GetCorreo() string {
	if x != nil {
		return x.Correo
	}
	return ""
}

func (x *UpdateMyProfileRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

type UpdateMyProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usuario       *Usuario               `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileResponse) Reset() {
	*x = UpdateMyProfileResponse{}
	mi := &file_usuarios_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileResponse) ProtoMessage() {}

func (x *UpdateMyProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usuarios_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileResponse) Descriptor() ([]byte, []int) {
	return file_usuarios_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMyProfileResponse) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

var File_usuarios_service_proto protoreflect.FileDescriptor

const file_usuarios_service_proto_rawDesc = "" +
	"\n" +
	"\x16usuarios_service.proto\x12\busuarios\"\xae\x02\n" +
	"\aUsuario\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anombres\x18\x02 \x01(\tR\anombres\x12\x1c\n" +
	"\tapellidos\x18\x03 \x01(\tR\tapellidos\x12\x10\n" +
	"\x03dni\x18\x04 \x01(\tR\x03dni\x12\x1a\n" +
	"\btelefono\x18\x05 \x01(\tR\btelefono\x12\x16\n" +
	"\x06correo\x18\x06 \x01(\tR\x06correo\x12\x1c\n" +
	"\tdireccion\x18\a \x01(\tR\tdireccion\x12!\n" +
	"\ftipo_usuario\x18\b \x01(\tR\vtipoUsuario\x12\x16\n" +
	"\x06activo\x18\t \x01(\bR\x06activo\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xb4\x01\n" +
	"\fUsuarioBasic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anombres\x18\x02 \x01(\tR\anombres\x12\x1c\n" +
	"\tapellidos\x18\x03 \x01(\tR\tapellidos\x12'\n" +
	"\x0fnombre_completo\x18\x04 \x01(\tR\x0enombreCompleto\x12!\n" +
	"\ftipo_usuario\x18\x05 \x01(\tR\vtipoUsuario\x12\x10\n" +
	"\x03dni\x18\x06 \x01(\tR\x03dni\"#\n" +
	"\x11GetUsuarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x12GetUsuarioResponse\x12+\n" +
	"\ausuario\x18\x01 \x01(\v2\x11.usuarios.UsuarioR\ausuario\"(\n" +
	"\x16GetUsuarioBasicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x17GetUsuarioBasicResponse\x120\n" +
	"\ausuario\x18\x01 \x01(\v2\x16.usuarios.UsuarioBasicR\ausuario\"+\n" +
	"\x17GetUsuariosBasicRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"N\n" +
	"\x18GetUsuariosBasicResponse\x122\n" +
	"\busuarios\x18\x01 \x03(\v2\x16.usuarios.UsuarioBasicR\busuarios\"i\n" +
	"\x13ListUsuariosRequest\x12!\n" +
	"\ftipo_usuario\x18\x01 \x01(\tR\vtipoUsuario\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"[\n" +
	"\x14ListUsuariosResponse\x12-\n" +
	"\busuarios\x18\x01 \x03(\v2\x11.usuarios.UsuarioR\busuarios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x81\x01\n" +
	"\x15SearchUsuariosRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\ftipo_usuario\x18\x02 \x01(\tR\vtipoUsuario\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"]\n" +
	"\x16SearchUsuariosResponse\x12-\n" +
	"\busuarios\x18\x01 \x03(\v2\x11.usuarios.UsuarioR\busuarios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe5\x01\n" +
	"\x14UpsertUsuarioRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\anombres\x18\x02 \x01(\tR\anombres\x12\x1c\n" +
	"\tapellidos\x18\x03 \x01(\tR\tapellidos\x12\x10\n" +
	"\x03dni\x18\x04 \x01(\tR\x03dni\x12\x1a\n" +
	"\btelefono\x18\x05 \x01(\tR\btelefono\x12\x16\n" +
	"\x06correo\x18\x06 \x01(\tR\x06correo\x12\x1c\n" +
	"\tdireccion\x18\a \x01(\tR\tdireccion\x12!\n" +
	"\ftipo_usuario\x18\b \x01(\tR\vtipoUsuario\"D\n" +
	"\x15UpsertUsuarioResponse\x12+\n" +
	"\ausuario\x18\x01 \x01(\v2\x11.usuarios.UsuarioR\ausuario\"j\n" +
	"\x16UpdateMyProfileRequest\x12\x1a\n" +
	"\btelefono\x18\x01 \x01(\tR\btelefono\x12\x16\n" +
	"\x06correo\x18\x02 \x01(\tR\x06correo\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\"F\n" +
	"\x17UpdateMyProfileResponse\x12+\n" +
	"\ausuario\x18\x01 \x01(\v2\x11.usuarios.UsuarioR\ausuario2\xd4\x04\n" +
	"\bUsuarios\x12G\n" +
	"\n" +
	"GetUsuario\x12\x1b.usuarios.GetUsuarioRequest\x1a\x1c.usuarios.GetUsuarioResponse\x12V\n" +
	"\x0fGetUsuarioBasic\x12 .usuarios.GetUsuarioBasicRequest\x1a!.usuarios.GetUsuarioBasicResponse\x12Y\n" +
	"\x10GetUsuariosBasic\x12!.usuarios.GetUsuariosBasicRequest\x1a\".usuarios.GetUsuariosBasicResponse\x12M\n" +
	"\fListUsuarios\x12\x1d.usuarios.ListUsuariosRequest\x1a\x1e.usuarios.ListUsuariosResponse\x12S\n" +
	"\x0eSearchUsuarios\x12\x1f.usuarios.SearchUsuariosRequest\x1a .usuarios.SearchUsuariosResponse\x12P\n" +
	"\rUpsertUsuario\x12\x1e.usuarios.UpsertUsuarioRequest\x1a\x1f.usuarios.UpsertUsuarioResponse\x12V\n" +
	"\x0fUpdateMyProfile\x12 .usuarios.UpdateMyProfileRequest\x1a!.usuarios.UpdateMyProfileResponseB\fZ\n" +
	"./usuariosb\x06proto3"

var (
	file_usuarios_service_proto_rawDescOnce sync.Once
	file_usuarios_service_proto_rawDescData []byte
)

func file_usuarios_service_proto_rawDescGZIP() []byte {
	file_usuarios_service_proto_rawDescOnce.Do(func() {
		file_usuarios_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usuarios_service_proto_rawDesc), len(file_usuarios_service_proto_rawDesc)))
	})
	return file_usuarios_service_proto_rawDescData
}

var file_usuarios_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_usuarios_service_proto_goTypes = []any{
	(*Usuario)(nil),                  // 0: usuarios.Usuario
	(*UsuarioBasic)(nil),             // 1: usuarios.UsuarioBasic
	(*GetUsuarioRequest)(nil),        // 2: usuarios.GetUsuarioRequest
	(*GetUsuarioResponse)(nil),       // 3: usuarios.GetUsuarioResponse
	(*GetUsuarioBasicRequest)(nil),   // 4: usuarios.GetUsuarioBasicRequest
	(*GetUsuarioBasicResponse)(nil),  // 5: usuarios.GetUsuarioBasicResponse
	(*GetUsuariosBasicRequest)(nil),  // 6: usuarios.GetUsuariosBasicRequest
	(*GetUsuariosBasicResponse)(nil), // 7: usuarios.GetUsuariosBasicResponse
	(*ListUsuariosRequest)(nil),      // 8: usuarios.ListUsuariosRequest
	(*ListUsuariosResponse)(nil),     // 9: usuarios.ListUsuariosResponse
	(*SearchUsuariosRequest)(nil),    // 10: usuarios.SearchUsuariosRequest
	(*SearchUsuariosResponse)(nil),   // 11: usuarios.SearchUsuariosResponse
	(*UpsertUsuarioRequest)(nil),     // 12: usuarios.UpsertUsuarioRequest
	(*UpsertUsuarioResponse)(nil),    // 13: usuarios.UpsertUsuarioResponse
	(*UpdateMyProfileRequest)(nil),   // 14: usuarios.UpdateMyProfileRequest
	(*UpdateMyProfileResponse)(nil),  // 15: usuarios.UpdateMyProfileResponse
}
var file_usuarios_service_proto_depIdxs = []int32{
	0,  // 0: usuarios.GetUsuarioResponse.usuario:type_name -> usuarios.Usuario
	1,  // 1: usuarios.GetUsuarioBasicResponse.usuario:type_name -> usuarios.UsuarioBasic
	1,  // 2: usuarios.GetUsuariosBasicResponse.usuarios:type_name -> usuarios.UsuarioBasic
	0,  // 3: usuarios.ListUsuariosResponse.usuarios:type_name -> usuarios.Usuario
	0,  // 4: usuarios.SearchUsuariosResponse.usuarios:type_name -> usuarios.Usuario
	0,  // 5: usuarios.UpsertUsuarioResponse.usuario:type_name -> usuarios.Usuario
	0,  // 6: usuarios.UpdateMyProfileResponse.usuario:type_name -> usuarios.Usuario
	2,  // 7: usuarios.Usuarios.GetUsuario:input_type -> usuarios.GetUsuarioRequest
	4,  // 8: usuarios.Usuarios.GetUsuarioBasic:input_type -> usuarios.GetUsuarioBasicRequest
	6,  // 9: usuarios.Usuarios.GetUsuariosBasic:input_type -> usuarios.GetUsuariosBasicRequest
	8,  // 10: usuarios.Usuarios.ListUsuarios:input_type -> usuarios.ListUsuariosRequest
	10, // 11: usuarios.Usuarios.SearchUsuarios:input_type -> usuarios.SearchUsuariosRequest
	12, // 12: usuarios.Usuarios.UpsertUsuario:input_type -> usuarios.UpsertUsuarioRequest
	14, // 13: usuarios.Usuarios.UpdateMyProfile:input_type -> usuarios.UpdateMyProfileRequest
	3,  // 14: usuarios.Usuarios.GetUsuario:output_type -> usuarios.GetUsuarioResponse
	5,  // 15: usuarios.Usuarios.GetUsuarioBasic:output_type -> usuarios.GetUsuarioBasicResponse
	7,  // 16: usuarios.Usuarios.GetUsuariosBasic:output_type -> usuarios.GetUsuariosBasicResponse
	9,  // 17: usuarios.Usuarios.ListUsuarios:output_type -> usuarios.ListUsuariosResponse
	11, // 18: usuarios.Usuarios.SearchUsuarios:output_type -> usuarios.SearchUsuariosResponse
	13, // 19: usuarios.Usuarios.UpsertUsuario:output_type -> usuarios.UpsertUsuarioResponse
	15, // 20: usuarios.Usuarios.UpdateMyProfile:output_type -> usuarios.UpdateMyProfileResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_usuarios_service_proto_init() }
func file_usuarios_service_proto_init() {
	if File_usuarios_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usuarios_service_proto_rawDesc), len(file_usuarios_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usuarios_service_proto_goTypes,
		DependencyIndexes: file_usuarios_service_proto_depIdxs,
		MessageInfos:      file_usuarios_service_proto_msgTypes,
	}.Build()
	File_usuarios_service_proto = out.File
	file_usuarios_service_proto_goTypes = nil
	file_usuarios_service_proto_depIdxs = nil
}
