// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: usuarios_service.proto

package usuarios

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Usuarios_GetUsuario_FullMethodName       = "/usuarios.Usuarios/GetUsuario"
	Usuarios_GetUsuarioBasic_FullMethodName  = "/usuarios.Usuarios/GetUsuarioBasic"
	Usuarios_GetUsuariosBasic_FullMethodName = "/usuarios.Usuarios/GetUsuariosBasic"
	Usuarios_ListUsuarios_FullMethodName     = "/usuarios.Usuarios/ListUsuarios"
	Usuarios_SearchUsuarios_FullMethodName   = "/usuarios.Usuarios/SearchUsuarios"
	Usuarios_UpsertUsuario_FullMethodName    = "/usuarios.Usuarios/UpsertUsuario"
	Usuarios_UpdateMyProfile_FullMethodName  = "/usuarios.Usuarios/UpdateMyProfile"
)

// UsuariosClient is the client API for Usuarios service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsuariosClient interface {
	GetUsuario(ctx context.Context, in *GetUsuarioRequest, opts ...grpc.CallOption) (*GetUsuarioResponse, error)
	GetUsuarioBasic(ctx context.Context, in *GetUsuarioBasicRequest, opts ...grpc.CallOption) (*GetUsuarioBasicResponse, error)
	GetUsuariosBasic(ctx context.Context, in *GetUsuariosBasicRequest, opts ...grpc.CallOption) (*GetUsuariosBasicResponse, error)
	ListUsuarios(ctx context.Context, in *ListUsuariosRequest, opts ...grpc.CallOption) (*ListUsuariosResponse, error)
	SearchUsuarios(ctx context.Context, in *SearchUsuariosRequest, opts ...grpc.CallOption) (*SearchUsuariosResponse, error)
	UpsertUsuario(ctx context.Context, in *UpsertUsuarioRequest, opts ...grpc.CallOption) (*UpsertUsuarioResponse, error)
	UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UpdateMyProfileResponse, error)
}

type usuariosClient struct {
	cc grpc.ClientConnInterface
}

func NewUsuariosClient(cc grpc.ClientConnInterface) UsuariosClient {
	return &usuariosClient{cc}
}

func (c *usuariosClient) GetUsuario(ctx context.Context, in *GetUsuarioRequest, opts ...grpc.CallOption) (*GetUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsuarioResponse)
	err := c.cc.Invoke(ctx, Usuarios_GetUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) GetUsuarioBasic(ctx context.Context, in *GetUsuarioBasicRequest, opts ...grpc.CallOption) (*GetUsuarioBasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsuarioBasicResponse)
	err := c.cc.Invoke(ctx, Usuarios_GetUsuarioBasic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) GetUsuariosBasic(ctx context.Context, in *GetUsuariosBasicRequest, opts ...grpc.CallOption) (*GetUsuariosBasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsuariosBasicResponse)
	err := c.cc.Invoke(ctx, Usuarios_GetUsuariosBasic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) ListUsuarios(ctx context.Context, in *ListUsuariosRequest, opts ...grpc.CallOption) (*ListUsuariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsuariosResponse)
	err := c.cc.Invoke(ctx, Usuarios_ListUsuarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) SearchUsuarios(ctx context.Context, in *SearchUsuariosRequest, opts ...grpc.CallOption) (*SearchUsuariosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsuariosResponse)
	err := c.cc.Invoke(ctx, Usuarios_SearchUsuarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) UpsertUsuario(ctx context.Context, in *UpsertUsuarioRequest, opts ...grpc.CallOption) (*UpsertUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertUsuarioResponse)
	err := c.cc.Invoke(ctx, Usuarios_UpsertUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UpdateMyProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMyProfileResponse)
	err := c.cc.Invoke(ctx, Usuarios_UpdateMyProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsuariosServer is the server API for Usuarios service.
// All implementations must embed UnimplementedUsuariosServer
// for forward compatibility.
type UsuariosServer interface {
	GetUsuario(context.Context, *GetUsuarioRequest) (*GetUsuarioResponse, error)
	GetUsuarioBasic(context.Context, *GetUsuarioBasicRequest) (*GetUsuarioBasicResponse, error)
	GetUsuariosBasic(context.Context, *GetUsuariosBasicRequest) (*GetUsuariosBasicResponse, error)
	ListUsuarios(context.Context, *ListUsuariosRequest) (*ListUsuariosResponse, error)
	SearchUsuarios(context.Context, *SearchUsuariosRequest) (*SearchUsuariosResponse, error)
	UpsertUsuario(context.Context, *UpsertUsuarioRequest) (*UpsertUsuarioResponse, error)
	UpdateMyProfile(context.Context, *UpdateMyProfileRequest) (*UpdateMyProfileResponse, error)
	mustEmbedUnimplementedUsuariosServer()
}

// UnimplementedUsuariosServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsuariosServer struct{}

func (UnimplementedUsuariosServer) GetUsuario(context.Context, *GetUsuarioRequest) (*GetUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsuario not implemented")
}
func (UnimplementedUsuariosServer) GetUsuarioBasic(context.Context, *GetUsuarioBasicRequest) (*GetUsuarioBasicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsuarioBasic not implemented")
}
func (UnimplementedUsuariosServer) GetUsuariosBasic(context.Context, *GetUsuariosBasicRequest) (*GetUsuariosBasicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsuariosBasic not implemented")
}
func (UnimplementedUsuariosServer) ListUsuarios(context.Context, *ListUsuariosRequest) (*ListUsuariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsuarios not implemented")
}
func (UnimplementedUsuariosServer) SearchUsuarios(context.Context, *SearchUsuariosRequest) (*SearchUsuariosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsuarios not implemented")
}
func (UnimplementedUsuariosServer) UpsertUsuario(context.Context, *UpsertUsuarioRequest) (*UpsertUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertUsuario not implemented")
}
func (UnimplementedUsuariosServer) UpdateMyProfile(context.Context, *UpdateMyProfileRequest) (*UpdateMyProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMyProfile not implemented")
}
func (UnimplementedUsuariosServer) mustEmbedUnimplementedUsuariosServer() {}
func (UnimplementedUsuariosServer) testEmbeddedByValue()                  {}

// UnsafeUsuariosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsuariosServer will
// result in compilation errors.
type UnsafeUsuariosServer interface {
	mustEmbedUnimplementedUsuariosServer()
}

func RegisterUsuariosServer(s grpc.ServiceRegistrar, srv UsuariosServer) {
	// If the following call panics, it indicates UnimplementedUsuariosServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Usuarios_ServiceDesc, srv)
}

func _Usuarios_GetUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).GetUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_GetUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).GetUsuario(ctx, req.(*GetUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_GetUsuarioBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsuarioBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).GetUsuarioBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_GetUsuarioBasic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).GetUsuarioBasic(ctx, req.(*GetUsuarioBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_GetUsuariosBasic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsuariosBasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).GetUsuariosBasic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_GetUsuariosBasic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).GetUsuariosBasic(ctx, req.(*GetUsuariosBasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_ListUsuarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsuariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).ListUsuarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_ListUsuarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).ListUsuarios(ctx, req.(*ListUsuariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_SearchUsuarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsuariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).SearchUsuarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_SearchUsuarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).SearchUsuarios(ctx, req.(*SearchUsuariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_UpsertUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).UpsertUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_UpsertUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).UpsertUsuario(ctx, req.(*UpsertUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_UpdateMyProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).UpdateMyProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usuarios_UpdateMyProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).UpdateMyProfile(ctx, req.(*UpdateMyProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Usuarios_ServiceDesc is the grpc.ServiceDesc for Usuarios service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usuarios_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usuarios.Usuarios",
	HandlerType: (*UsuariosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsuario",
			Handler:    _Usuarios_GetUsuario_Handler,
		},
		{
			MethodName: "GetUsuarioBasic",
			Handler:    _Usuarios_GetUsuarioBasic_Handler,
		},
		{
			MethodName: "GetUsuariosBasic",
			Handler:    _Usuarios_GetUsuariosBasic_Handler,
		},
		{
			MethodName: "ListUsuarios",
			Handler:    _Usuarios_ListUsuarios_Handler,
		},
		{
			MethodName: "SearchUsuarios",
			Handler:    _Usuarios_SearchUsuarios_Handler,
		},
		{
			MethodName: "UpsertUsuario",
			Handler:    _Usuarios_UpsertUsuario_Handler,
		},
		{
			MethodName: "UpdateMyProfile",
			Handler:    _Usuarios_UpdateMyProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usuarios_service.proto",
}
