// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ChangeEstadoRequest struct {
	Authorization string `header:"Authorization,optional"`
	Id            string `path:"id"`
	NuevoEstado   string `json:"nuevo_estado"`
}

type ChangeEstadoResponse struct {
	Expediente ExpedienteDTO `json:"expediente"`
}

type CreateExpedienteRequest struct {
	Authorization string `header:"Authorization,optional"`
	Tipo          string `json:"tipo,optional"`
	Asunto        string `json:"asunto"`
	Descripcion   string `json:"descripcion,optional"`
	Prioridad     string `json:"prioridad,optional"`
}

type CreateExpedienteResponse struct {
	Expediente ExpedienteDTO `json:"expediente"`
}

type ExpedienteDTO struct {
	Id                 string `json:"id"`
	Codigo             string `json:"codigo"`
	Tipo               string `json:"tipo"`
	Asunto             string `json:"asunto"`
	Descripcion        string `json:"descripcion"`
	SolicitanteId      string `json:"solicitante_id"`
	Estado             string `json:"estado"`
	Prioridad          string `json:"prioridad"`
	FechaRegistro      string `json:"fecha_registro"`
	FechaActualizacion string `json:"fecha_actualizacion"`
	Activo             bool   `json:"activo"`
}

type GetExpedienteRequest struct {
	Authorization string `header:"Authorization,optional"`
	Id            string `path:"id"`
}

type GetExpedienteResponse struct {
	Expediente ExpedienteDTO `json:"expediente"`
}

type GetUsuarioBasicRequest struct {
	Authorization string `header:"Authorization,optional"`
	Id            string `path:"id"`
}

type GetUsuarioBasicResponse struct {
	Usuario UsuarioBasicDTO `json:"usuario"`
}

type GetUsuarioRequest struct {
	Authorization string `header:"Authorization,optional"`
	Id            string `path:"id"`
}

type GetUsuarioResponse struct {
	Usuario UsuarioDTO `json:"usuario"`
}

type GetUsuariosBasicRequest struct {
	Authorization string   `header:"Authorization,optional"`
	Ids           []string `json:"ids"`
}

type GetUsuariosBasicResponse struct {
	Usuarios []UsuarioBasicDTO `json:"usuarios"`
}

type ListExpedientesRequest struct {
	Authorization string `header:"Authorization,optional"`
	Estado        string `form:"estado,optional"`
	Prioridad     string `form:"prioridad,optional"`
	Tipo          string `form:"tipo,optional"`
	Page          int32  `form:"page,optional"`
	PageSize      int32  `form:"page_size,optional"`
}

type ListExpedientesResponse struct {
	Expedientes []ExpedienteDTO `json:"expedientes"`
	Total       int32           `json:"total"`
}

type ListUsuariosRequest struct {
	Authorization string `header:"Authorization,optional"`
	Q             string `form:"q,optional"`
	TipoUsuario   string `form:"tipo_usuario,optional"`
	Page          int32  `form:"page,optional"`
	PageSize      int32  `form:"page_size,optional"`
}

type ListUsuariosResponse struct {
	Usuarios []UsuarioDTO `json:"usuarios"`
	Total    int32        `json:"total"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
	UserId       string `json:"user_id"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Role         string `json:"role"`
}

type LogoutRequest struct {
	Authorization string `header:"Authorization,optional"`
	RefreshToken  string `json:"refresh_token"`
}

type LogoutResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role,optional"`
}

type RegisterResponse struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Role     string `json:"role"`
	Message  string `json:"message"`
}

type UpdateExpedienteRequest struct {
	Authorization string `header:"Authorization,optional"`
	Id            string `path:"id"`
	Asunto        string `json:"asunto"`
	Descripcion   string `json:"descripcion,optional"`
	Prioridad     string `json:"prioridad,optional"`
}

type UpdateExpedienteResponse struct {
	Expediente ExpedienteDTO `json:"expediente"`
}

type UsuarioBasicDTO struct {
	Id             string `json:"id"`
	Nombres        string `json:"nombres"`
	Apellidos      string `json:"apellidos"`
	NombreCompleto string `json:"nombre_completo"`
	TipoUsuario    string `json:"tipo_usuario"`
	Dni            string `json:"dni"`
}

type UsuarioDTO struct {
	Id          string `json:"id"`
	Nombres     string `json:"nombres"`
	Apellidos   string `json:"apellidos"`
	Dni         string `json:"dni"`
	Telefono    string `json:"telefono"`
	Correo      string `json:"correo"`
	Direccion   string `json:"direccion"`
	TipoUsuario string `json:"tipo_usuario"`
	Activo      bool   `json:"activo"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type ValidateTokenRequest struct {
	Authorization string `header:"Authorization,optional"`
}

type ValidateTokenResponse struct {
	Valid    bool   `json:"valid"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
	Role     string `json:"role"`
}
