// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: documentos_service.proto

package documentosclient

import (
	"context"

	"documentos/documentos"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteDocumentoRequest    = documentos.DeleteDocumentoRequest
	DeleteDocumentoResponse   = documentos.DeleteDocumentoResponse
	Documento                 = documentos.Documento
	DownloadDocumentoRequest  = documentos.DownloadDocumentoRequest
	DownloadDocumentoResponse = documentos.DownloadDocumentoResponse
	GetDocumentoRequest       = documentos.GetDocumentoRequest
	GetDocumentoResponse      = documentos.GetDocumentoResponse
	ListDocumentosRequest     = documentos.ListDocumentosRequest
	ListDocumentosResponse    = documentos.ListDocumentosResponse
	UploadDocumentoRequest    = documentos.UploadDocumentoRequest
	UploadDocumentoResponse   = documentos.UploadDocumentoResponse

	Documentos interface {
		UploadDocumento(ctx context.Context, in *UploadDocumentoRequest, opts ...grpc.CallOption) (*UploadDocumentoResponse, error)
		GetDocumento(ctx context.Context, in *GetDocumentoRequest, opts ...grpc.CallOption) (*GetDocumentoResponse, error)
		DownloadDocumento(ctx context.Context, in *DownloadDocumentoRequest, opts ...grpc.CallOption) (*DownloadDocumentoResponse, error)
		ListDocumentos(ctx context.Context, in *ListDocumentosRequest, opts ...grpc.CallOption) (*ListDocumentosResponse, error)
		DeleteDocumento(ctx context.Context, in *DeleteDocumentoRequest, opts ...grpc.CallOption) (*DeleteDocumentoResponse, error)
	}

	defaultDocumentos struct {
		cli zrpc.Client
	}
)

func NewDocumentos(cli zrpc.Client) Documentos {
	return &defaultDocumentos{
		cli: cli,
	}
}

func (m *defaultDocumentos) UploadDocumento(ctx context.Context, in *UploadDocumentoRequest, opts ...grpc.CallOption) (*UploadDocumentoResponse, error) {
	client := documentos.NewDocumentosClient(m.cli.Conn())
	return client.UploadDocumento(ctx, in, opts...)
}

func (m *defaultDocumentos) GetDocumento(ctx context.Context, in *GetDocumentoRequest, opts ...grpc.CallOption) (*GetDocumentoResponse, error) {
	client := documentos.NewDocumentosClient(m.cli.Conn())
	return client.GetDocumento(ctx, in, opts...)
}

func (m *defaultDocumentos) DownloadDocumento(ctx context.Context, in *DownloadDocumentoRequest, opts ...grpc.CallOption) (*DownloadDocumentoResponse, error) {
	client := documentos.NewDocumentosClient(m.cli.Conn())
	return client.DownloadDocumento(ctx, in, opts...)
}

func (m *defaultDocumentos) ListDocumentos(ctx context.Context, in *ListDocumentosRequest, opts ...grpc.CallOption) (*ListDocumentosResponse, error) {
	client := documentos.NewDocumentosClient(m.cli.Conn())
	return client.ListDocumentos(ctx, in, opts...)
}

func (m *defaultDocumentos) DeleteDocumento(ctx context.Context, in *DeleteDocumentoRequest, opts ...grpc.CallOption) (*DeleteDocumentoResponse, error) {
	client := documentos.NewDocumentosClient(m.cli.Conn())
	return client.DeleteDocumento(ctx, in, opts...)
}
