// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: usuarios_service.proto

package server

import (
	"context"

	"usuarios/internal/logic"
	"usuarios/internal/svc"
	"usuarios/usuarios"
)

type UsuariosServer struct {
	svcCtx *svc.ServiceContext
	usuarios.UnimplementedUsuariosServer
}

func NewUsuariosServer(svcCtx *svc.ServiceContext) *UsuariosServer {
	return &UsuariosServer{
		svcCtx: svcCtx,
	}
}

func (s *UsuariosServer) GetUsuario(ctx context.Context, in *usuarios.GetUsuarioRequest) (*usuarios.GetUsuarioResponse, error) {
	l := logic.NewGetUsuarioLogic(ctx, s.svcCtx)
	return l.GetUsuario(in)
}

func (s *UsuariosServer) GetUsuarioBasic(ctx context.Context, in *usuarios.GetUsuarioBasicRequest) (*usuarios.GetUsuarioBasicResponse, error) {
	l := logic.NewGetUsuarioBasicLogic(ctx, s.svcCtx)
	return l.GetUsuarioBasic(in)
}

func (s *UsuariosServer) GetUsuariosBasic(ctx context.Context, in *usuarios.GetUsuariosBasicRequest) (*usuarios.GetUsuariosBasicResponse, error) {
	l := logic.NewGetUsuariosBasicLogic(ctx, s.svcCtx)
	return l.GetUsuariosBasic(in)
}

func (s *UsuariosServer) ListUsuarios(ctx context.Context, in *usuarios.ListUsuariosRequest) (*usuarios.ListUsuariosResponse, error) {
	l := logic.NewListUsuariosLogic(ctx, s.svcCtx)
	return l.ListUsuarios(in)
}

func (s *UsuariosServer) SearchUsuarios(ctx context.Context, in *usuarios.SearchUsuariosRequest) (*usuarios.SearchUsuariosResponse, error) {
	l := logic.NewSearchUsuariosLogic(ctx, s.svcCtx)
	return l.SearchUsuarios(in)
}

func (s *UsuariosServer) UpsertUsuario(ctx context.Context, in *usuarios.UpsertUsuarioRequest) (*usuarios.UpsertUsuarioResponse, error) {
	l := logic.NewUpsertUsuarioLogic(ctx, s.svcCtx)
	return l.UpsertUsuario(in)
}

func (s *UsuariosServer) UpdateMyProfile(ctx context.Context, in *usuarios.UpdateMyProfileRequest) (*usuarios.UpdateMyProfileResponse, error) {
	l := logic.NewUpdateMyProfileLogic(ctx, s.svcCtx)
	return l.UpdateMyProfile(in)
}
