// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: usuarios_service.proto

package usuariosclient

import (
	"context"

	"usuarios/usuarios"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUsuarioBasicRequest   = usuarios.GetUsuarioBasicRequest
	GetUsuarioBasicResponse  = usuarios.GetUsuarioBasicResponse
	GetUsuarioRequest        = usuarios.GetUsuarioRequest
	GetUsuarioResponse       = usuarios.GetUsuarioResponse
	GetUsuariosBasicRequest  = usuarios.GetUsuariosBasicRequest
	GetUsuariosBasicResponse = usuarios.GetUsuariosBasicResponse
	ListUsuariosRequest      = usuarios.ListUsuariosRequest
	ListUsuariosResponse     = usuarios.ListUsuariosResponse
	SearchUsuariosRequest    = usuarios.SearchUsuariosRequest
	SearchUsuariosResponse   = usuarios.SearchUsuariosResponse
	UpsertUsuarioRequest     = usuarios.UpsertUsuarioRequest
	UpsertUsuarioResponse    = usuarios.UpsertUsuarioResponse
	UpdateMyProfileRequest   = usuarios.UpdateMyProfileRequest
	UpdateMyProfileResponse  = usuarios.UpdateMyProfileResponse
	Usuario                  = usuarios.Usuario
	UsuarioBasic             = usuarios.UsuarioBasic

	Usuarios interface {
		GetUsuario(ctx context.Context, in *GetUsuarioRequest, opts ...grpc.CallOption) (*GetUsuarioResponse, error)
		GetUsuarioBasic(ctx context.Context, in *GetUsuarioBasicRequest, opts ...grpc.CallOption) (*GetUsuarioBasicResponse, error)
		GetUsuariosBasic(ctx context.Context, in *GetUsuariosBasicRequest, opts ...grpc.CallOption) (*GetUsuariosBasicResponse, error)
		ListUsuarios(ctx context.Context, in *ListUsuariosRequest, opts ...grpc.CallOption) (*ListUsuariosResponse, error)
		SearchUsuarios(ctx context.Context, in *SearchUsuariosRequest, opts ...grpc.CallOption) (*SearchUsuariosResponse, error)
		UpsertUsuario(ctx context.Context, in *UpsertUsuarioRequest, opts ...grpc.CallOption) (*UpsertUsuarioResponse, error)
		UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UpdateMyProfileResponse, error)
	}

	defaultUsuarios struct {
		cli zrpc.Client
	}
)

func NewUsuarios(cli zrpc.Client) Usuarios {
	return &defaultUsuarios{
		cli: cli,
	}
}

func (m *defaultUsuarios) GetUsuario(ctx context.Context, in *GetUsuarioRequest, opts ...grpc.CallOption) (*GetUsuarioResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.GetUsuario(ctx, in, opts...)
}

func (m *defaultUsuarios) GetUsuarioBasic(ctx context.Context, in *GetUsuarioBasicRequest, opts ...grpc.CallOption) (*GetUsuarioBasicResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.GetUsuarioBasic(ctx, in, opts...)
}

func (m *defaultUsuarios) GetUsuariosBasic(ctx context.Context, in *GetUsuariosBasicRequest, opts ...grpc.CallOption) (*GetUsuariosBasicResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.GetUsuariosBasic(ctx, in, opts...)
}

func (m *defaultUsuarios) ListUsuarios(ctx context.Context, in *ListUsuariosRequest, opts ...grpc.CallOption) (*ListUsuariosResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.ListUsuarios(ctx, in, opts...)
}

func (m *defaultUsuarios) SearchUsuarios(ctx context.Context, in *SearchUsuariosRequest, opts ...grpc.CallOption) (*SearchUsuariosResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.SearchUsuarios(ctx, in, opts...)
}

func (m *defaultUsuarios) UpsertUsuario(ctx context.Context, in *UpsertUsuarioRequest, opts ...grpc.CallOption) (*UpsertUsuarioResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.UpsertUsuario(ctx, in, opts...)
}

func (m *defaultUsuarios) UpdateMyProfile(ctx context.Context, in *UpdateMyProfileRequest, opts ...grpc.CallOption) (*UpdateMyProfileResponse, error) {
	client := usuarios.NewUsuariosClient(m.cli.Conn())
	return client.UpdateMyProfile(ctx, in, opts...)
}
