// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: expedientes_service.proto

package expedientesclient

import (
	"context"

	"expedientes/expedientes"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangeEstadoRequest      = expedientes.ChangeEstadoRequest
	ChangeEstadoResponse     = expedientes.ChangeEstadoResponse
	CreateExpedienteRequest  = expedientes.CreateExpedienteRequest
	CreateExpedienteResponse = expedientes.CreateExpedienteResponse
	DeleteExpedienteRequest  = expedientes.DeleteExpedienteRequest
	DeleteExpedienteResponse = expedientes.DeleteExpedienteResponse
	Expediente               = expedientes.Expediente
	GetExpedienteRequest     = expedientes.GetExpedienteRequest
	GetExpedienteResponse    = expedientes.GetExpedienteResponse
	ListExpedientesRequest   = expedientes.ListExpedientesRequest
	ListExpedientesResponse  = expedientes.ListExpedientesResponse
	UpdateExpedienteRequest  = expedientes.UpdateExpedienteRequest
	UpdateExpedienteResponse = expedientes.UpdateExpedienteResponse

	Expedientes interface {
		CreateExpediente(ctx context.Context, in *CreateExpedienteRequest, opts ...grpc.CallOption) (*CreateExpedienteResponse, error)
		GetExpediente(ctx context.Context, in *GetExpedienteRequest, opts ...grpc.CallOption) (*GetExpedienteResponse, error)
		ListExpedientes(ctx context.Context, in *ListExpedientesRequest, opts ...grpc.CallOption) (*ListExpedientesResponse, error)
		UpdateExpediente(ctx context.Context, in *UpdateExpedienteRequest, opts ...grpc.CallOption) (*UpdateExpedienteResponse, error)
		ChangeEstado(ctx context.Context, in *ChangeEstadoRequest, opts ...grpc.CallOption) (*ChangeEstadoResponse, error)
		DeleteExpediente(ctx context.Context, in *DeleteExpedienteRequest, opts ...grpc.CallOption) (*DeleteExpedienteResponse, error)
	}

	defaultExpedientes struct {
		cli zrpc.Client
	}
)

func NewExpedientes(cli zrpc.Client) Expedientes {
	return &defaultExpedientes{
		cli: cli,
	}
}

func (m *defaultExpedientes) CreateExpediente(ctx context.Context, in *CreateExpedienteRequest, opts ...grpc.CallOption) (*CreateExpedienteResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.CreateExpediente(ctx, in, opts...)
}

func (m *defaultExpedientes) GetExpediente(ctx context.Context, in *GetExpedienteRequest, opts ...grpc.CallOption) (*GetExpedienteResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.GetExpediente(ctx, in, opts...)
}

func (m *defaultExpedientes) ListExpedientes(ctx context.Context, in *ListExpedientesRequest, opts ...grpc.CallOption) (*ListExpedientesResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.ListExpedientes(ctx, in, opts...)
}

func (m *defaultExpedientes) UpdateExpediente(ctx context.Context, in *UpdateExpedienteRequest, opts ...grpc.CallOption) (*UpdateExpedienteResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.UpdateExpediente(ctx, in, opts...)
}

func (m *defaultExpedientes) ChangeEstado(ctx context.Context, in *ChangeEstadoRequest, opts ...grpc.CallOption) (*ChangeEstadoResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.ChangeEstado(ctx, in, opts...)
}

func (m *defaultExpedientes) DeleteExpediente(ctx context.Context, in *DeleteExpedienteRequest, opts ...grpc.CallOption) (*DeleteExpedienteResponse, error) {
	client := expedientes.NewExpedientesClient(m.cli.Conn())
	return client.DeleteExpediente(ctx, in, opts...)
}
