// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: derivaciones_service.proto

package derivacionesclient

import (
	"context"

	"derivaciones/derivaciones"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CrearDerivacionRequest   = derivaciones.CrearDerivacionRequest
	CrearDerivacionResponse  = derivaciones.CrearDerivacionResponse
	Derivacion               = derivaciones.Derivacion
	GetDerivacionRequest     = derivaciones.GetDerivacionRequest
	GetDerivacionResponse    = derivaciones.GetDerivacionResponse
	ListDerivacionesRequest  = derivaciones.ListDerivacionesRequest
	ListDerivacionesResponse = derivaciones.ListDerivacionesResponse

	Derivaciones interface {
		CrearDerivacion(ctx context.Context, in *CrearDerivacionRequest, opts ...grpc.CallOption) (*CrearDerivacionResponse, error)
		GetDerivacion(ctx context.Context, in *GetDerivacionRequest, opts ...grpc.CallOption) (*GetDerivacionResponse, error)
		ListDerivaciones(ctx context.Context, in *ListDerivacionesRequest, opts ...grpc.CallOption) (*ListDerivacionesResponse, error)
	}

	defaultDerivaciones struct {
		cli zrpc.Client
	}
)

func NewDerivaciones(cli zrpc.Client) Derivaciones {
	return &defaultDerivaciones{
		cli: cli,
	}
}

func (m *defaultDerivaciones) CrearDerivacion(ctx context.Context, in *CrearDerivacionRequest, opts ...grpc.CallOption) (*CrearDerivacionResponse, error) {
	client := derivaciones.NewDerivacionesClient(m.cli.Conn())
	return client.CrearDerivacion(ctx, in, opts...)
}

func (m *defaultDerivaciones) GetDerivacion(ctx context.Context, in *GetDerivacionRequest, opts ...grpc.CallOption) (*GetDerivacionResponse, error) {
	client := derivaciones.NewDerivacionesClient(m.cli.Conn())
	return client.GetDerivacion(ctx, in, opts...)
}

func (m *defaultDerivaciones) ListDerivaciones(ctx context.Context, in *ListDerivacionesRequest, opts ...grpc.CallOption) (*ListDerivacionesResponse, error) {
	client := derivaciones.NewDerivacionesClient(m.cli.Conn())
	return client.ListDerivaciones(ctx, in, opts...)
}
