// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/validate",
				Handler: ValidateTokenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/usuarios",
				Handler: ListUsuariosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/usuarios/:id",
				Handler: GetUsuarioHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/usuarios/:id/basic",
				Handler: GetUsuarioBasicHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/usuarios/basic-batch",
				Handler: GetUsuariosBasicHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/expedientes",
				Handler: CreateExpedienteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/expedientes",
				Handler: ListExpedientesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/expedientes/:id",
				Handler: GetExpedienteHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/expedientes/:id",
				Handler: UpdateExpedienteHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/api/expedientes/:id/estado",
				Handler: ChangeEstadoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/documentos",
				Handler: UploadDocumentoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/documentos/:id",
				Handler: GetDocumentoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/documentos/:id",
				Handler: DeleteDocumentoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/documentos/:id/contenido",
				Handler: DownloadDocumentoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/expedientes/:expediente_id/documentos",
				Handler: ListDocumentosByExpedienteHandler(serverCtx),
			},
		},
	)
}
