// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: expedientes_service.proto

package server

import (
	"context"

	"expedientes/expedientes"
	"expedientes/internal/logic"
	"expedientes/internal/svc"
)

type ExpedientesServer struct {
	svcCtx *svc.ServiceContext
	expedientes.UnimplementedExpedientesServer
}

func NewExpedientesServer(svcCtx *svc.ServiceContext) *ExpedientesServer {
	return &ExpedientesServer{
		svcCtx: svcCtx,
	}
}

func (s *ExpedientesServer) CreateExpediente(ctx context.Context, in *expedientes.CreateExpedienteRequest) (*expedientes.CreateExpedienteResponse, error) {
	l := logic.NewCreateExpedienteLogic(ctx, s.svcCtx)
	return l.CreateExpediente(in)
}

func (s *ExpedientesServer) GetExpediente(ctx context.Context, in *expedientes.GetExpedienteRequest) (*expedientes.GetExpedienteResponse, error) {
	l := logic.NewGetExpedienteLogic(ctx, s.svcCtx)
	return l.GetExpediente(in)
}

func (s *ExpedientesServer) ListExpedientes(ctx context.Context, in *expedientes.ListExpedientesRequest) (*expedientes.ListExpedientesResponse, error) {
	l := logic.NewListExpedientesLogic(ctx, s.svcCtx)
	return l.ListExpedientes(in)
}

func (s *ExpedientesServer) UpdateExpediente(ctx context.Context, in *expedientes.UpdateExpedienteRequest) (*expedientes.UpdateExpedienteResponse, error) {
	l := logic.NewUpdateExpedienteLogic(ctx, s.svcCtx)
	return l.UpdateExpediente(in)
}

func (s *ExpedientesServer) ChangeEstado(ctx context.Context, in *expedientes.ChangeEstadoRequest) (*expedientes.ChangeEstadoResponse, error) {
	l := logic.NewChangeEstadoLogic(ctx, s.svcCtx)
	return l.ChangeEstado(in)
}

func (s *ExpedientesServer) DeleteExpediente(ctx context.Context, in *expedientes.DeleteExpedienteRequest) (*expedientes.DeleteExpedienteResponse, error) {
	l := logic.NewDeleteExpedienteLogic(ctx, s.svcCtx)
	return l.DeleteExpediente(in)
}

func (s *ExpedientesServer) UpdateArea(ctx context.Context, in *expedientes.UpdateAreaRequest) (*expedientes.UpdateAreaResponse, error) {
	l := logic.NewUpdateAreaLogic(ctx, s.svcCtx)
	return l.UpdateArea(in)
}

func (s *ExpedientesServer) DerivarExpediente(ctx context.Context, in *expedientes.DerivarExpedienteRequest) (*expedientes.DerivarExpedienteResponse, error) {
	l := logic.NewDerivarExpedienteLogic(ctx, s.svcCtx)
	return l.DerivarExpediente(in)
}

func (s *ExpedientesServer) RechazarExpediente(ctx context.Context, in *expedientes.RechazarExpedienteRequest) (*expedientes.RechazarExpedienteResponse, error) {
	l := logic.NewRechazarExpedienteLogic(ctx, s.svcCtx)
	return l.RechazarExpediente(in)
}

func (s *ExpedientesServer) CorregirExpediente(ctx context.Context, in *expedientes.CorregirExpedienteRequest) (*expedientes.CorregirExpedienteResponse, error) {
	l := logic.NewCorregirExpedienteLogic(ctx, s.svcCtx)
	return l.CorregirExpediente(in)
}

func (s *ExpedientesServer) ResolverExpediente(ctx context.Context, in *expedientes.ResolverExpedienteRequest) (*expedientes.ResolverExpedienteResponse, error) {
	l := logic.NewResolverExpedienteLogic(ctx, s.svcCtx)
	return l.ResolverExpediente(in)
}

func (s *ExpedientesServer) ValidateDerivacion(ctx context.Context, in *expedientes.ValidateDerivacionRequest) (*expedientes.ValidateDerivacionResponse, error) {
	l := logic.NewValidateDerivacionLogic(ctx, s.svcCtx)
	return l.ValidateDerivacion(in)
}
