// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: derivaciones_service.proto

package derivaciones

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Derivacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpedienteId  string                 `protobuf:"bytes,2,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Origen        string                 `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino       string                 `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Motivo        string                 `protobuf:"bytes,6,opt,name=motivo,proto3" json:"motivo,omitempty"`
	Condicion     string                 `protobuf:"bytes,7,opt,name=condicion,proto3" json:"condicion,omitempty"`
	RegistradoPor string                 `protobuf:"bytes,8,opt,name=registrado_por,json=registradoPor,proto3" json:"registrado_por,omitempty"`
	FechaRegistro string                 `protobuf:"bytes,9,opt,name=fecha_registro,json=fechaRegistro,proto3" json:"fecha_registro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Derivacion) Reset() {
	*x = Derivacion{}
	mi := &file_derivaciones_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Derivacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Derivacion) ProtoMessage() {}

func (x *Derivacion) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Derivacion.ProtoReflect.Descriptor instead.
func (*Derivacion) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{0}
}

func (x *Derivacion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Derivacion) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

func (x *Derivacion) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Derivacion) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Derivacion) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Derivacion) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *Derivacion) GetCondicion() string {
	if x != nil {
		return x.Condicion
	}
	return ""
}

func (x *Derivacion) GetRegistradoPor() string {
	if x != nil {
		return x.RegistradoPor
	}
	return ""
}

func (x *Derivacion) GetFechaRegistro() string {
	if x != nil {
		return x.FechaRegistro
	}
	return ""
}

type CrearDerivacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpedienteId  string                 `protobuf:"bytes,1,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Origen        string                 `protobuf:"bytes,3,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino       string                 `protobuf:"bytes,4,opt,name=destino,proto3" json:"destino,omitempty"`
	Motivo        string                 `protobuf:"bytes,5,opt,name=motivo,proto3" json:"motivo,omitempty"`
	Condicion     string                 `protobuf:"bytes,6,opt,name=condicion,proto3" json:"condicion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearDerivacionRequest) Reset() {
	*x = CrearDerivacionRequest{}
	mi := &file_derivaciones_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearDerivacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearDerivacionRequest) ProtoMessage() {}

func (x *CrearDerivacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearDerivacionRequest.ProtoReflect.Descriptor instead.
func (*CrearDerivacionRequest) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{1}
}

func (x *CrearDerivacionRequest) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

func (x *CrearDerivacionRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *CrearDerivacionRequest) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *CrearDerivacionRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *CrearDerivacionRequest) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *CrearDerivacionRequest) GetCondicion() string {
	if x != nil {
		return x.Condicion
	}
	return ""
}

type CrearDerivacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Derivacion    *Derivacion            `protobuf:"bytes,1,opt,name=derivacion,proto3" json:"derivacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearDerivacionResponse) Reset() {
	*x = CrearDerivacionResponse{}
	mi := &file_derivaciones_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearDerivacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearDerivacionResponse) ProtoMessage() {}

func (x *CrearDerivacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearDerivacionResponse.ProtoReflect.Descriptor instead.
func (*CrearDerivacionResponse) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{2}
}

func (x *CrearDerivacionResponse) GetDerivacion() *Derivacion {
	if x != nil {
		return x.Derivacion
	}
	return nil
}

type GetDerivacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDerivacionRequest) Reset() {
	*x = GetDerivacionRequest{}
	mi := &file_derivaciones_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDerivacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDerivacionRequest) ProtoMessage() {}

func (x *GetDerivacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDerivacionRequest.ProtoReflect.Descriptor instead.
func (*GetDerivacionRequest) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetDerivacionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDerivacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Derivacion    *Derivacion            `protobuf:"bytes,1,opt,name=derivacion,proto3" json:"derivacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDerivacionResponse) Reset() {
	*x = GetDerivacionResponse{}
	mi := &file_derivaciones_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDerivacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDerivacionResponse) ProtoMessage() {}

func (x *GetDerivacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDerivacionResponse.ProtoReflect.Descriptor instead.
func (*GetDerivacionResponse) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDerivacionResponse) GetDerivacion() *Derivacion {
	if x != nil {
		return x.Derivacion
	}
	return nil
}

type ListDerivacionesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expediente_id vacio = listar de todos los expedientes (solo personal
	// interno, ver internal/authorization.CanViewAll). Con valor, filtra a
	// ese expediente puntual.
	ExpedienteId  string `protobuf:"bytes,1,opt,name=expediente_id,json=expedienteId,proto3" json:"expediente_id,omitempty"`
	Tipo          string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDerivacionesRequest) Reset() {
	*x = ListDerivacionesRequest{}
	mi := &file_derivaciones_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDerivacionesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDerivacionesRequest) ProtoMessage() {}

func (x *ListDerivacionesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDerivacionesRequest.ProtoReflect.Descriptor instead.
func (*ListDerivacionesRequest) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListDerivacionesRequest) GetExpedienteId() string {
	if x != nil {
		return x.ExpedienteId
	}
	return ""
}

func (x *ListDerivacionesRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *ListDerivacionesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDerivacionesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDerivacionesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Derivaciones  []*Derivacion          `protobuf:"bytes,1,rep,name=derivaciones,proto3" json:"derivaciones,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDerivacionesResponse) Reset() {
	*x = ListDerivacionesResponse{}
	mi := &file_derivaciones_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDerivacionesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDerivacionesResponse) ProtoMessage() {}

func (x *ListDerivacionesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_derivaciones_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDerivacionesResponse.ProtoReflect.Descriptor instead.
func (*ListDerivacionesResponse) Descriptor() ([]byte, []int) {
	return file_derivaciones_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDerivacionesResponse) GetDerivaciones() []*Derivacion {
	if x != nil {
		return x.Derivaciones
	}
	return nil
}

func (x *ListDerivacionesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_derivaciones_service_proto protoreflect.FileDescriptor

const file_derivaciones_service_proto_rawDesc = "" +
	"\n" +
	"\x1aderivaciones_service.proto\x12\fderivaciones\"\x8b\x02\n" +
	"\n" +
	"Derivacion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rexpediente_id\x18\x02 \x01(\tR\fexpedienteId\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06origen\x18\x04 \x01(\tR\x06origen\x12\x18\n" +
	"\adestino\x18\x05 \x01(\tR\adestino\x12\x16\n" +
	"\x06motivo\x18\x06 \x01(\tR\x06motivo\x12\x1c\n" +
	"\tcondicion\x18\a \x01(\tR\tcondicion\x12%\n" +
	"\x0eregistrado_por\x18\b \x01(\tR\rregistradoPor\x12%\n" +
	"\x0efecha_registro\x18\t \x01(\tR\rfechaRegistro\"\xb9\x01\n" +
	"\x16CrearDerivacionRequest\x12#\n" +
	"\rexpediente_id\x18\x01 \x01(\tR\fexpedienteId\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x16\n" +
	"\x06origen\x18\x03 \x01(\tR\x06origen\x12\x18\n" +
	"\adestino\x18\x04 \x01(\tR\adestino\x12\x16\n" +
	"\x06motivo\x18\x05 \x01(\tR\x06motivo\x12\x1c\n" +
	"\tcondicion\x18\x06 \x01(\tR\tcondicion\"S\n" +
	"\x17CrearDerivacionResponse\x128\n" +
	"\n" +
	"derivacion\x18\x01 \x01(\v2\x18.derivaciones.DerivacionR\n" +
	"derivacion\"&\n" +
	"\x14GetDerivacionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x15GetDerivacionResponse\x128\n" +
	"\n" +
	"derivacion\x18\x01 \x01(\v2\x18.derivaciones.DerivacionR\n" +
	"derivacion\"\x83\x01\n" +
	"\x17ListDerivacionesRequest\x12#\n" +
	"\rexpediente_id\x18\x01 \x01(\tR\fexpedienteId\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"n\n" +
	"\x18ListDerivacionesResponse\x12<\n" +
	"\fderivaciones\x18\x01 \x03(\v2\x18.derivaciones.DerivacionR\fderivaciones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xab\x02\n" +
	"\fDerivaciones\x12^\n" +
	"\x0fCrearDerivacion\x12$.derivaciones.CrearDerivacionRequest\x1a%.derivaciones.CrearDerivacionResponse\x12X\n" +
	"\rGetDerivacion\x12\".derivaciones.GetDerivacionRequest\x1a#.derivaciones.GetDerivacionResponse\x12a\n" +
	"\x10ListDerivaciones\x12%.derivaciones.ListDerivacionesRequest\x1a&.derivaciones.ListDerivacionesResponseB\x10Z\x0e./derivacionesb\x06proto3"

var (
	file_derivaciones_service_proto_rawDescOnce sync.Once
	file_derivaciones_service_proto_rawDescData []byte
)

func file_derivaciones_service_proto_rawDescGZIP() []byte {
	file_derivaciones_service_proto_rawDescOnce.Do(func() {
		file_derivaciones_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_derivaciones_service_proto_rawDesc), len(file_derivaciones_service_proto_rawDesc)))
	})
	return file_derivaciones_service_proto_rawDescData
}

var file_derivaciones_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_derivaciones_service_proto_goTypes = []any{
	(*Derivacion)(nil),               // 0: derivaciones.Derivacion
	(*CrearDerivacionRequest)(nil),   // 1: derivaciones.CrearDerivacionRequest
	(*CrearDerivacionResponse)(nil),  // 2: derivaciones.CrearDerivacionResponse
	(*GetDerivacionRequest)(nil),     // 3: derivaciones.GetDerivacionRequest
	(*GetDerivacionResponse)(nil),    // 4: derivaciones.GetDerivacionResponse
	(*ListDerivacionesRequest)(nil),  // 5: derivaciones.ListDerivacionesRequest
	(*ListDerivacionesResponse)(nil), // 6: derivaciones.ListDerivacionesResponse
}
var file_derivaciones_service_proto_depIdxs = []int32{
	0, // 0: derivaciones.CrearDerivacionResponse.derivacion:type_name -> derivaciones.Derivacion
	0, // 1: derivaciones.GetDerivacionResponse.derivacion:type_name -> derivaciones.Derivacion
	0, // 2: derivaciones.ListDerivacionesResponse.derivaciones:type_name -> derivaciones.Derivacion
	1, // 3: derivaciones.Derivaciones.CrearDerivacion:input_type -> derivaciones.CrearDerivacionRequest
	3, // 4: derivaciones.Derivaciones.GetDerivacion:input_type -> derivaciones.GetDerivacionRequest
	5, // 5: derivaciones.Derivaciones.ListDerivaciones:input_type -> derivaciones.ListDerivacionesRequest
	2, // 6: derivaciones.Derivaciones.CrearDerivacion:output_type -> derivaciones.CrearDerivacionResponse
	4, // 7: derivaciones.Derivaciones.GetDerivacion:output_type -> derivaciones.GetDerivacionResponse
	6, // 8: derivaciones.Derivaciones.ListDerivaciones:output_type -> derivaciones.ListDerivacionesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_derivaciones_service_proto_init() }
func file_derivaciones_service_proto_init() {
	if File_derivaciones_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derivaciones_service_proto_rawDesc), len(file_derivaciones_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_derivaciones_service_proto_goTypes,
		DependencyIndexes: file_derivaciones_service_proto_depIdxs,
		MessageInfos:      file_derivaciones_service_proto_msgTypes,
	}.Build()
	File_derivaciones_service_proto = out.File
	file_derivaciones_service_proto_goTypes = nil
	file_derivaciones_service_proto_depIdxs = nil
}
