// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: derivaciones_service.proto

package derivaciones

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Derivaciones_CrearDerivacion_FullMethodName  = "/derivaciones.Derivaciones/CrearDerivacion"
	Derivaciones_GetDerivacion_FullMethodName    = "/derivaciones.Derivaciones/GetDerivacion"
	Derivaciones_ListDerivaciones_FullMethodName = "/derivaciones.Derivaciones/ListDerivaciones"
)

// DerivacionesClient is the client API for Derivaciones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DerivacionesClient interface {
	CrearDerivacion(ctx context.Context, in *CrearDerivacionRequest, opts ...grpc.CallOption) (*CrearDerivacionResponse, error)
	GetDerivacion(ctx context.Context, in *GetDerivacionRequest, opts ...grpc.CallOption) (*GetDerivacionResponse, error)
	ListDerivaciones(ctx context.Context, in *ListDerivacionesRequest, opts ...grpc.CallOption) (*ListDerivacionesResponse, error)
}

type derivacionesClient struct {
	cc grpc.ClientConnInterface
}

func NewDerivacionesClient(cc grpc.ClientConnInterface) DerivacionesClient {
	return &derivacionesClient{cc}
}

func (c *derivacionesClient) CrearDerivacion(ctx context.Context, in *CrearDerivacionRequest, opts ...grpc.CallOption) (*CrearDerivacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearDerivacionResponse)
	err := c.cc.Invoke(ctx, Derivaciones_CrearDerivacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *derivacionesClient) GetDerivacion(ctx context.Context, in *GetDerivacionRequest, opts ...grpc.CallOption) (*GetDerivacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDerivacionResponse)
	err := c.cc.Invoke(ctx, Derivaciones_GetDerivacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *derivacionesClient) ListDerivaciones(ctx context.Context, in *ListDerivacionesRequest, opts ...grpc.CallOption) (*ListDerivacionesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDerivacionesResponse)
	err := c.cc.Invoke(ctx, Derivaciones_ListDerivaciones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DerivacionesServer is the server API for Derivaciones service.
// All implementations must embed UnimplementedDerivacionesServer
// for forward compatibility.
type DerivacionesServer interface {
	CrearDerivacion(context.Context, *CrearDerivacionRequest) (*CrearDerivacionResponse, error)
	GetDerivacion(context.Context, *GetDerivacionRequest) (*GetDerivacionResponse, error)
	ListDerivaciones(context.Context, *ListDerivacionesRequest) (*ListDerivacionesResponse, error)
	mustEmbedUnimplementedDerivacionesServer()
}

// UnimplementedDerivacionesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDerivacionesServer struct{}

func (UnimplementedDerivacionesServer) CrearDerivacion(context.Context, *CrearDerivacionRequest) (*CrearDerivacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearDerivacion not implemented")
}
func (UnimplementedDerivacionesServer) GetDerivacion(context.Context, *GetDerivacionRequest) (*GetDerivacionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDerivacion not implemented")
}
func (UnimplementedDerivacionesServer) ListDerivaciones(context.Context, *ListDerivacionesRequest) (*ListDerivacionesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDerivaciones not implemented")
}
func (UnimplementedDerivacionesServer) mustEmbedUnimplementedDerivacionesServer() {}
func (UnimplementedDerivacionesServer) testEmbeddedByValue()                      {}

// UnsafeDerivacionesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DerivacionesServer will
// result in compilation errors.
type UnsafeDerivacionesServer interface {
	mustEmbedUnimplementedDerivacionesServer()
}

func RegisterDerivacionesServer(s grpc.ServiceRegistrar, srv DerivacionesServer) {
	// If the following call panics, it indicates UnimplementedDerivacionesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Derivaciones_ServiceDesc, srv)
}

func _Derivaciones_CrearDerivacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearDerivacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DerivacionesServer).CrearDerivacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Derivaciones_CrearDerivacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DerivacionesServer).CrearDerivacion(ctx, req.(*CrearDerivacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Derivaciones_GetDerivacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDerivacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DerivacionesServer).GetDerivacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Derivaciones_GetDerivacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DerivacionesServer).GetDerivacion(ctx, req.(*GetDerivacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Derivaciones_ListDerivaciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDerivacionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DerivacionesServer).ListDerivaciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Derivaciones_ListDerivaciones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DerivacionesServer).ListDerivaciones(ctx, req.(*ListDerivacionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Derivaciones_ServiceDesc is the grpc.ServiceDesc for Derivaciones service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Derivaciones_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "derivaciones.Derivaciones",
	HandlerType: (*DerivacionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearDerivacion",
			Handler:    _Derivaciones_CrearDerivacion_Handler,
		},
		{
			MethodName: "GetDerivacion",
			Handler:    _Derivaciones_GetDerivacion_Handler,
		},
		{
			MethodName: "ListDerivaciones",
			Handler:    _Derivaciones_ListDerivaciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "derivaciones_service.proto",
}
